CREATE TABLE input_catapult_activities_periods(load_timestamp DATETIME DEFAULT GETDATE(),
id NVARCHAR(MAX),
activity_id NVARCHAR(MAX),
period_depth_id NVARCHAR(MAX),
name NVARCHAR(MAX),
start_time NVARCHAR(MAX),
start_centiseconds NVARCHAR(MAX),
end_time NVARCHAR(MAX),
end_centiseconds NVARCHAR(MAX),
lft NVARCHAR(MAX),
rgt NVARCHAR(MAX),
is_synced NVARCHAR(MAX),
is_deleted NVARCHAR(MAX),
is_injected NVARCHAR(MAX),
created_at NVARCHAR(MAX),
modified_at NVARCHAR(MAX),
user_id NVARCHAR(MAX))