CREATE TABLE input_catapult_activities(load_timestamp DATETIME DEFAULT GETDATE(),
id NVARCHAR(MAX),
name NVARCHAR(MAX),
start_time NVARCHAR(MAX),
end_time NVARCHAR(MAX),
modified_at NVARCHAR(MAX),
game_id NVARCHAR(MAX),
owner_id NVARCHAR(MAX),
tag_list NVARCHAR(MAX),
athlete_count NVARCHAR(MAX),
period_count NVARCHAR(MAX),
activity_athletes NVARCHAR(MAX),
venue_name NVARCHAR(MAX),
venue_width NVARCHAR(MAX),
venue_length NVARCHAR(MAX),
venue_rotation NVARCHAR(MAX),
venue_lat NVARCHAR(MAX),
venue_lng NVARCHAR(MAX))