CREATE TABLE input_catapult_positions(load_timestamp DATETIME DEFAULT GETDATE(),
id NVARCHAR(100),
name NVARCHAR(100),
slug NVARCHAR(10),
sport_id NVARCHAR(100),
sport_name NVARCHAR(100),
created_at DATETIME,
modified_at DATETIME,
tag_list NVARCHAR(500),
tags NVARCHAR(500))