CREATE TABLE input_catapult_events_running_symmetry(load_timestamp DATETIME DEFAULT GETDATE(),
activity_id NVARCHAR(100),
period_id NVARCHAR(100),
athlete_id NVARCHAR(100),
start_time NUMERIC(12,2),
end_time NUMERIC(12,2),
version NVARCHAR(10),
foostrikes INT,
imbalance NUMERIC(10,5),
distance NUMERIC(10,5),
line_deviation NUMERIC(10,5),
avg_velocity NUMERIC(10,5),
max_velocity NUMERIC(10,5))