CREATE TABLE input_catapult_events(load_timestamp DATETIME DEFAULT GETDATE(),
activity_id NVARCHAR(MAX),
period_id NVARCHAR(MAX),
athlete_id NVARCHAR(MAX),
device_id NVARCHAR(MAX),
player_id NVARCHAR(MAX),
athlete_first_name NVARCHAR(MAX),
athlete_last_name NVARCHAR(MAX),
jersey NVARCHAR(MAX),
team_id NVARCHAR(MAX),
team_name NVARCHAR(MAX),
data NVARCHAR(MAX))