CREATE TABLE input_catapult_stats_1_test ( load_timestamp DATETIME DEFAULT GETDATE()
,[athlete_id] NVARCHAR(100)
,[date_id] date
,[date_name] date
,[is_injected] NVARCHAR(10)
,[is_demo_data] NVARCHAR(10)
,[athlete_weight] INT
,[activity_id] NVARCHAR(100)
,[activity_name] NVARCHAR(100)
,[athlete_jersey] NVARCHAR(10)
,[period_id] NVARCHAR(100)
,[period_name] NVARCHAR(10)
,[start_time] INT
,[end_time] INT
,[position_name] NVARCHAR(100)
,[team_name] NVARCHAR(50)
,[month_name] NVARCHAR(10)
,[day_name] NVARCHAR(10)
,[field_time] INT
,[bench_time] INT
,[median_time_to_feet] INT
,[total_distance] NUMERIC(10,5)
,[total_duration] INT
,[peak_player_load] NUMERIC(10,5)
,[total_player_load] NUMERIC(10,5)
,[total_2d_player_load] NUMERIC(10,5)
,[total_slow_player_load] NUMERIC(10,5)
,[total_1d_fwd_player_load] NUMERIC(10,5)
,[total_1d_side_player_load] NUMERIC(10,5)
,[total_1d_up_player_load] NUMERIC(10,4)
,[velocity_exertion] NUMERIC(10,5)
,[heart_rate_exertion] INT
,[max_heart_rate] INT
,[min_heart_rate] INT
,[max_vel] NUMERIC(10,5)
,[peak_meta_power] NUMERIC(10,5)
,[equivalent_distance] NUMERIC(10,5)
,[max_effort_acceleration] NUMERIC(10,5)
,[max_effort_deceleration] NUMERIC(10,5)
,[total_acceleration_load] NUMERIC(10,5)
,[running_series_count] INT
,[running_total_footstrikes] INT
,[running_standard_deviation] INT
,[running_strike_weighted_imbalance] NUMERIC(10,5)
,[total_gnss_quality] NUMERIC(12,5)
,[min_gnss_quality] NUMERIC(10,5)
,[max_gnss_quality] NUMERIC(10,5)
,[gnss_quality_sample_count] INT
,[total_hdop] NUMERIC(10,5)
,[min_hdop] NUMERIC(10,5)
,[max_hdop] NUMERIC(10,5)
,[hdop_sample_count] INT
,[total_satellite_count] INT
,[min_satellite_count] INT
,[max_satellite_count] INT
,[satellite_sample_count] INT
,[total_dive_load] INT
,[total_goalkeeping_dives] INT
,[total_dives_left] INT
,[total_dives_right] INT
,[total_dives_centre] INT
,[total_time_to_feet_left] INT
,[total_time_to_feet_right] INT
,[total_time_to_feet_centre] INT
,[total_dive_load_left] INT
,[total_dive_load_right] INT
,[total_dive_load_centre] INT
,[fmp_very_low_duration] NUMERIC(10,5)
,[fmp_low_duration] NUMERIC(10,5)
,[fmp_running_med_duration] INT
,[fmp_running_high_duration] INT
,[fmp_running_total_duration] INT
,[fmp_dynamic_med_duration] INT
,[fmp_dynamic_high_duration] INT
,[fmp_dynamic_total_duration] INT
,[fmp_total_duration] NVARCHAR(100)
,[velocity_band1_total_distance] NUMERIC(10,5)
,[velocity_band1_total_duration] NUMERIC(10,5)
,[velocity_band2_total_distance] NUMERIC(10,5)
,[velocity_band2_total_duration] NUMERIC(10,5)
,[velocity_band2_total_effort_count] INT
,[velocity_band2_min_effort_distance] NUMERIC(10,5)
,[velocity_band2_max_effort_distance] NUMERIC(10,5)
,[velocity_band2_min_effort_duration] NUMERIC(10,5)
,[velocity_band2_max_effort_duration] NUMERIC(10,5)
,[velocity_band2_recovery_band1_total_effort_count] INT
,[velocity_band2_distance_band1_total_effort_count] INT
,[velocity_band2_recovery_band2_total_effort_count] INT
,[velocity_band2_distance_band2_total_effort_count] INT
,[velocity_band2_recovery_band3_total_effort_count] INT
,[velocity_band2_distance_band3_total_effort_count] INT
,[velocity_band2_recovery_band4_total_effort_count] INT
,[velocity_band2_distance_band4_total_effort_count] INT
,[velocity_band2_recovery_band5_total_effort_count] INT
,[velocity_band2_distance_band5_total_effort_count] INT
,[velocity_band2_recovery_band6_total_effort_count] INT
,[velocity_band2_distance_band6_total_effort_count] INT
,[velocity_band2_recovery_band7_total_effort_count] INT
,[velocity_band2_distance_band7_total_effort_count] INT
,[velocity_band2_recovery_band8_total_effort_count] INT
,[velocity_band2_distance_band8_total_effort_count] INT
,[velocity_band3_total_distance] NUMERIC(10,5)
,[velocity_band3_total_duration] NUMERIC(10,5)
,[velocity_band3_total_effort_count] INT
,[velocity_band3_min_effort_distance] NUMERIC(10,5)
,[velocity_band3_max_effort_distance] NUMERIC(10,5)
,[velocity_band3_min_effort_duration] NUMERIC(10,5)
,[velocity_band3_max_effort_duration] NUMERIC(10,5)
,[velocity_band3_recovery_band1_total_effort_count] INT
,[velocity_band3_distance_band1_total_effort_count] INT
,[velocity_band3_recovery_band2_total_effort_count] INT
,[velocity_band3_distance_band2_total_effort_count] INT
,[velocity_band3_recovery_band3_total_effort_count] INT
,[velocity_band3_distance_band3_total_effort_count] INT
,[velocity_band3_recovery_band4_total_effort_count] INT
,[velocity_band3_distance_band4_total_effort_count] INT
,[velocity_band3_recovery_band5_total_effort_count] INT
,[velocity_band3_distance_band5_total_effort_count] INT
,[velocity_band3_recovery_band6_total_effort_count] INT
,[velocity_band3_distance_band6_total_effort_count] INT
,[velocity_band3_recovery_band7_total_effort_count] INT
,[velocity_band3_distance_band7_total_effort_count] INT
,[velocity_band3_recovery_band8_total_effort_count] INT
,[velocity_band3_distance_band8_total_effort_count] INT
,[velocity_band4_total_distance] NUMERIC(10,5)
,[velocity_band4_total_duration] NUMERIC(10,5)
,[velocity_band4_total_effort_count] INT
,[velocity_band4_min_effort_distance] NUMERIC(10,5)
,[velocity_band4_max_effort_distance] NUMERIC(10,5)
,[velocity_band4_min_effort_duration] NUMERIC(10,5)
,[velocity_band4_max_effort_duration] NUMERIC(10,5)
,[velocity_band4_recovery_band1_total_effort_count] INT
,[velocity_band4_distance_band1_total_effort_count] INT
,[velocity_band4_recovery_band2_total_effort_count] INT
,[velocity_band4_distance_band2_total_effort_count] INT
,[velocity_band4_recovery_band3_total_effort_count] INT
,[velocity_band4_distance_band3_total_effort_count] INT
,[velocity_band4_recovery_band4_total_effort_count] INT
,[velocity_band4_distance_band4_total_effort_count] INT
,[velocity_band4_recovery_band5_total_effort_count] INT
,[velocity_band4_distance_band5_total_effort_count] INT
,[velocity_band4_recovery_band6_total_effort_count] INT
,[velocity_band4_distance_band6_total_effort_count] INT
,[velocity_band4_recovery_band7_total_effort_count] INT
,[velocity_band4_distance_band7_total_effort_count] INT
,[velocity_band4_recovery_band8_total_effort_count] INT
,[velocity_band4_distance_band8_total_effort_count] INT
,[velocity_band5_total_distance] NUMERIC(10,5)
,[velocity_band5_total_duration] NUMERIC(10,5)
,[velocity_band5_total_effort_count] INT
,[velocity_band5_min_effort_distance] NUMERIC(10,5)
,[velocity_band5_max_effort_distance] NUMERIC(10,5)
,[velocity_band5_min_effort_duration] NUMERIC(10,5)
,[velocity_band5_max_effort_duration] NUMERIC(10,5)
,[velocity_band5_recovery_band1_total_effort_count] INT
,[velocity_band5_distance_band1_total_effort_count] INT
,[velocity_band5_recovery_band2_total_effort_count] INT
,[velocity_band5_distance_band2_total_effort_count] INT
,[velocity_band5_recovery_band3_total_effort_count] INT
,[velocity_band5_distance_band3_total_effort_count] INT
,[velocity_band5_recovery_band4_total_effort_count] INT
,[velocity_band5_distance_band4_total_effort_count] INT
,[velocity_band5_recovery_band5_total_effort_count] INT
,[velocity_band5_distance_band5_total_effort_count] INT
,[velocity_band5_recovery_band6_total_effort_count] INT
,[velocity_band5_distance_band6_total_effort_count] INT
,[velocity_band5_recovery_band7_total_effort_count] INT
,[velocity_band5_distance_band7_total_effort_count] INT
,[velocity_band5_recovery_band8_total_effort_count] INT
,[velocity_band5_distance_band8_total_effort_count] INT
,[velocity_band6_total_distance] NUMERIC(10,5)
,[velocity_band6_total_duration] NUMERIC(10,5)
,[velocity_band6_total_effort_count] INT
,[velocity_band6_min_effort_distance] NUMERIC(10,5)
,[velocity_band6_max_effort_distance] NUMERIC(10,5)
,[velocity_band6_min_effort_duration] NUMERIC(10,5)
,[velocity_band6_max_effort_duration] NUMERIC(10,5)
,[velocity_band6_recovery_band1_total_effort_count] INT
,[velocity_band6_distance_band1_total_effort_count] INT
,[velocity_band6_recovery_band2_total_effort_count] INT
,[velocity_band6_distance_band2_total_effort_count] INT
,[velocity_band6_recovery_band3_total_effort_count] INT
,[velocity_band6_distance_band3_total_effort_count] INT
,[velocity_band6_recovery_band4_total_effort_count] INT
,[velocity_band6_distance_band4_total_effort_count] INT
,[velocity_band6_recovery_band5_total_effort_count] INT
,[velocity_band6_distance_band5_total_effort_count] INT
,[velocity_band6_recovery_band6_total_effort_count] INT
,[velocity_band6_distance_band6_total_effort_count] INT
,[velocity_band6_recovery_band7_total_effort_count] INT
,[velocity_band6_distance_band7_total_effort_count] INT
,[velocity_band6_recovery_band8_total_effort_count] INT
,[velocity_band6_distance_band8_total_effort_count] INT
,[velocity_band7_total_distance] NUMERIC(10,5)
,[velocity_band7_total_duration] NUMERIC(10,5)
,[velocity_band7_total_effort_count] INT
,[velocity_band7_min_effort_distance] NUMERIC(10,5)
,[velocity_band7_max_effort_distance] NUMERIC(10,5)
,[velocity_band7_min_effort_duration] NUMERIC(10,5)
,[velocity_band7_max_effort_duration] NUMERIC(10,5)
,[velocity_band7_recovery_band1_total_effort_count] INT
,[velocity_band7_distance_band1_total_effort_count] INT
,[velocity_band7_recovery_band2_total_effort_count] INT
,[velocity_band7_distance_band2_total_effort_count] INT
,[velocity_band7_recovery_band3_total_effort_count] INT
,[velocity_band7_distance_band3_total_effort_count] INT
,[velocity_band7_recovery_band4_total_effort_count] INT
,[velocity_band7_distance_band4_total_effort_count] INT
,[velocity_band7_recovery_band5_total_effort_count] INT
,[velocity_band7_distance_band5_total_effort_count] INT
,[velocity_band7_recovery_band6_total_effort_count] INT
,[velocity_band7_distance_band6_total_effort_count] INT
,[velocity_band7_recovery_band7_total_effort_count] INT
,[velocity_band7_distance_band7_total_effort_count] INT
,[velocity_band7_recovery_band8_total_effort_count] INT
,[velocity_band7_distance_band8_total_effort_count] INT
,[velocity_band8_total_distance] NUMERIC(10,5)
,[velocity_band8_total_duration] NUMERIC(10,5)
,[velocity_band8_total_effort_count] INT
,[velocity_band8_min_effort_distance] NUMERIC(10,5)
,[velocity_band8_max_effort_distance] NUMERIC(10,5)
,[velocity_band8_min_effort_duration] NUMERIC(10,5)
,[velocity_band8_max_effort_duration] NUMERIC(10,5)
,[velocity_band8_recovery_band1_total_effort_count] INT
,[velocity_band8_distance_band1_total_effort_count] INT
,[velocity_band8_recovery_band2_total_effort_count] INT
,[velocity_band8_distance_band2_total_effort_count] INT
,[velocity_band8_recovery_band3_total_effort_count] INT
,[velocity_band8_distance_band3_total_effort_count] INT
,[velocity_band8_recovery_band4_total_effort_count] INT
,[velocity_band8_distance_band4_total_effort_count] INT
,[velocity_band8_recovery_band5_total_effort_count] INT
,[velocity_band8_distance_band5_total_effort_count] INT
,[velocity_band8_recovery_band6_total_effort_count] INT
,[velocity_band8_distance_band6_total_effort_count] INT
,[velocity_band8_recovery_band7_total_effort_count] INT
,[velocity_band8_distance_band7_total_effort_count] INT
,[velocity_band8_recovery_band8_total_effort_count] INT
,[velocity_band8_distance_band8_total_effort_count] INT
,[velocity2_band1_total_distance] NUMERIC(10,5)
,[velocity2_band2_total_distance] NUMERIC(10,5)
,[velocity2_band2_total_effort_count] INT
,[velocity2_band3_total_distance] NUMERIC(10,5)
,[velocity2_band3_total_effort_count] INT
,[velocity2_band4_total_distance] NUMERIC(10,5)
,[velocity2_band4_total_effort_count] INT
,[velocity2_band5_total_distance] NUMERIC(10,5)
,[velocity2_band5_total_effort_count] INT
,[velocity2_band6_total_distance] NUMERIC(10,5)
,[velocity2_band6_total_effort_count] INT
,[velocity2_band7_total_distance] NUMERIC(10,5)
,[velocity2_band7_total_effort_count] NUMERIC(10,5)
,[velocity2_band8_total_distance] INT
,[velocity2_band8_total_effort_count] INT
,[gen2_velocity_band2_total_effort_distance] NUMERIC(10,5)
,[gen2_velocity_band2_total_effort_count] INT
,[gen2_velocity_band3_total_effort_distance] NUMERIC(10,5)
,[gen2_velocity_band3_total_effort_count] INT
,[gen2_velocity_band4_total_effort_distance] NUMERIC(10,5)
,[gen2_velocity_band4_total_effort_count] INT
,[gen2_velocity_band4_min_effort_distance] NUMERIC(10,5)
,[gen2_velocity_band4_max_effort_distance] NUMERIC(10,5)
,[gen2_velocity_band5_total_effort_distance] NUMERIC(10,5)
,[gen2_velocity_band5_total_effort_count] INT
,[gen2_velocity_band5_min_effort_distance] NUMERIC(10,5)
,[gen2_velocity_band5_max_effort_distance] NUMERIC(10,5)
,[gen2_velocity_band6_total_effort_distance] NUMERIC(10,5)
,[gen2_velocity_band6_total_effort_count] INT
,[gen2_velocity_band6_min_effort_distance] NUMERIC(10,5)
,[gen2_velocity_band6_max_effort_distance] NUMERIC(10,5)
,[gen2_velocity_band7_total_effort_distance] NUMERIC(10,5)
,[gen2_velocity_band7_total_effort_count] INT
,[gen2_velocity_band7_min_effort_distance] NUMERIC(10,5)
,[gen2_velocity_band7_max_effort_distance] NUMERIC(10,5)
,[gen2_velocity_band8_total_effort_distance] NUMERIC(10,5)
,[gen2_velocity_band8_total_effort_count] INT
,[gen2_velocity_band8_min_effort_distance] NUMERIC(10,5)
,[gen2_velocity_band8_max_effort_distance] NUMERIC(10,5)
,[gen2_velocity2_band2_total_effort_distance] NUMERIC(10,5)
,[gen2_velocity2_band2_total_effort_count] INT
,[gen2_velocity2_band3_total_effort_distance] NUMERIC(10,5)
,[gen2_velocity2_band3_total_effort_count] INT
,[gen2_velocity2_band4_total_effort_distance] NUMERIC(10,5)
,[gen2_velocity2_band4_total_effort_count] INT
,[gen2_velocity2_band4_min_effort_distance] NUMERIC(10,5)
,[gen2_velocity2_band4_max_effort_distance] NUMERIC(10,5)
,[gen2_velocity2_band5_total_effort_distance] NUMERIC(10,5)
,[gen2_velocity2_band5_total_effort_count] INT
,[gen2_velocity2_band5_min_effort_distance] NUMERIC(10,5)
,[gen2_velocity2_band5_max_effort_distance] NUMERIC(10,5)
,[gen2_velocity2_band6_total_effort_distance] NUMERIC(10,5)
,[gen2_velocity2_band6_total_effort_count] INT
,[gen2_velocity2_band6_min_effort_distance] NUMERIC(10,5)
,[gen2_velocity2_band6_max_effort_distance] NUMERIC(10,5)
,[gen2_velocity2_band7_total_effort_distance] NUMERIC(10,5)
,[gen2_velocity2_band7_total_effort_count] INT
,[gen2_velocity2_band7_min_effort_distance] NUMERIC(10,5)
,[gen2_velocity2_band7_max_effort_distance] NUMERIC(10,5)
,[gen2_velocity2_band8_total_effort_distance] NUMERIC(10,5)
,[gen2_velocity2_band8_total_effort_count] INT
,[gen2_velocity2_band8_min_effort_distance] NUMERIC(10,5)
,[gen2_velocity2_band8_max_effort_distance] NUMERIC(10,5)
,[heart_rate_band1_total_distance] NUMERIC(10,5)
,[heart_rate_band1_total_duration] NUMERIC(10,5)
,[heart_rate_band2_total_distance] NUMERIC(10,5)
,[heart_rate_band2_total_duration] NUMERIC(10,5)
,[heart_rate_band2_total_effort_count] INT
,[heart_rate_band3_total_distance] NUMERIC(10,5)
,[heart_rate_band3_total_duration] NUMERIC(10,5)
,[heart_rate_band3_total_effort_count] INT
,[heart_rate_band4_total_distance] NUMERIC(10,5)
,[heart_rate_band4_total_duration] NUMERIC(10,5)
,[heart_rate_band4_total_effort_count] INT
,[heart_rate_band5_total_distance] NUMERIC(10,5)
,[heart_rate_band5_total_duration] NUMERIC(10,5)
,[heart_rate_band5_total_effort_count] INT
,[heart_rate_band6_total_distance] NUMERIC(10,5)
,[heart_rate_band6_total_duration] NUMERIC(10,5)
,[heart_rate_band6_total_effort_count] INT
,[heart_rate_band7_total_distance] NUMERIC(10,5)
,[heart_rate_band7_total_duration] NUMERIC(10,5)
,[heart_rate_band7_total_effort_count] INT
,[heart_rate_band8_total_distance] NUMERIC(10,5)
,[heart_rate_band8_total_duration] NUMERIC(10,5)
,[heart_rate_band8_total_effort_count] INT
,[acceleration_band1_total_distance] NUMERIC(10,5)
,[acceleration_band1_total_duration] NUMERIC(10,5)
,[acceleration_band1_total_effort_count] INT
,[acceleration_band2_total_distance] NUMERIC(10,5)
,[acceleration_band2_total_duration] NUMERIC(10,5)
,[acceleration_band2_total_effort_count] INT
,[acceleration_band3_total_distance] NUMERIC(10,5)
,[acceleration_band3_total_duration] NUMERIC(10,5)
,[acceleration_band3_total_effort_count] INT
,[acceleration_band4_total_distance] NUMERIC(10,5)
,[acceleration_band4_total_duration] NUMERIC(10,5)
,[acceleration_band4_total_effort_count] INT
,[acceleration_band5_total_distance] NUMERIC(10,5)
,[acceleration_band5_total_duration] NUMERIC(10,5)
,[acceleration_band5_total_effort_count] INT
,[acceleration_band6_total_distance] NUMERIC(10,5)
,[acceleration_band6_total_duration] NUMERIC(10,5)
,[acceleration_band6_total_effort_count] INT
,[acceleration_band7_total_distance] NUMERIC(10,5)
,[acceleration_band7_total_duration] NUMERIC(10,5)
,[acceleration_band7_total_effort_count] INT
,[acceleration_band8_total_distance] NUMERIC(10,5)
,[acceleration_band8_total_duration] NUMERIC(10,5)
,[acceleration_band8_total_effort_count] INT
,[player_load_band1_total_distance] NUMERIC(10,5)
,[player_load_band1_total_duration] NUMERIC(10,5)
,[player_load_band1_total_power] INT
,[player_load_band2_total_distance] NUMERIC(10,5)
,[player_load_band2_total_duration] NUMERIC(10,5)
,[player_load_band2_total_effort_count] INT
,[player_load_band2_total_power] INT
,[player_load_band3_total_distance] NUMERIC(10,5)
,[player_load_band3_total_duration] NUMERIC(10,5)
,[player_load_band3_total_effort_count] INT
,[player_load_band3_total_power] INT
,[player_load_band4_total_distance] NUMERIC(10,5)
,[player_load_band4_total_duration] NUMERIC(10,5)
,[player_load_band4_total_effort_count] INT
,[player_load_band4_total_power] INT
,[player_load_band5_total_distance] NUMERIC(10,5)
,[player_load_band5_total_duration] NUMERIC(10,5)
,[player_load_band5_total_effort_count] INT
,[player_load_band5_total_power] INT
,[player_load_band6_total_distance] NUMERIC(10,5)
,[player_load_band6_total_duration] NUMERIC(10,5)
,[player_load_band6_total_effort_count] INT
,[player_load_band6_total_power] INT
,[player_load_band7_total_distance] NUMERIC(10,5)
,[player_load_band7_total_duration] NUMERIC(10,5)
,[player_load_band7_total_effort_count] INT
,[player_load_band7_total_power] INT
,[player_load_band8_total_distance] NUMERIC(10,5)
,[player_load_band8_total_duration] NUMERIC(10,5)
,[player_load_band8_total_effort_count] INT
,[player_load_band8_total_power] INT
,[metabolic_power_band1_total_distance] NUMERIC(10,5)
,[metabolic_power_band1_total_duration] NUMERIC(10,5)
,[metabolic_power_band2_total_distance] NUMERIC(10,5)
,[metabolic_power_band2_total_duration] NUMERIC(10,5)
,[metabolic_power_band2_total_effort_count] INT
,[metabolic_power_band3_total_distance] NUMERIC(10,5)
,[metabolic_power_band3_total_duration] NUMERIC(10,5)
,[metabolic_power_band3_total_effort_count] INT
,[metabolic_power_band4_total_distance] NUMERIC(10,5)
,[metabolic_power_band4_total_duration] NUMERIC(10,5)
,[metabolic_power_band4_total_effort_count] INT
,[metabolic_power_band5_total_distance] NUMERIC(10,5)
,[metabolic_power_band5_total_duration] NUMERIC(10,5)
,[metabolic_power_band5_total_effort_count] INT
,[metabolic_power_band6_total_distance] NUMERIC(10,5)
,[metabolic_power_band6_total_duration] NUMERIC(10,5)
,[metabolic_power_band6_total_effort_count] INT
,[metabolic_power_band7_total_distance] NUMERIC(10,5)
,[metabolic_power_band7_total_duration] NUMERIC(10,5)
,[metabolic_power_band7_total_effort_count] INT
,[metabolic_power_band8_total_distance] NUMERIC(10,5)
,[metabolic_power_band8_total_duration] NUMERIC(10,5)
,[metabolic_power_band8_total_effort_count] INT
,[tackles_band1_total_count] INT
,[tackles_band2_total_count] INT
,[tackles_band3_total_count] INT
,[tackles_band4_total_count] INT
,[tackles_band5_total_count] INT
,[tackles_band6_total_count] INT
,[tackles_band7_total_count] INT
,[tackles_band8_total_count] INT
,[diveloadleft_band1_total_count] INT
,[diveloadleft_band1_total_pre_dive_load] INT
,[diveloadleft_band1_total_post_dive_load] INT
,[diveloadleft_band1_total_impact_dive_load] INT
,[diveloadleft_band2_total_count] INT
,[diveloadleft_band2_total_pre_dive_load] INT
,[diveloadleft_band2_total_post_dive_load] INT
,[diveloadleft_band2_total_impact_dive_load] INT
,[diveloadleft_band3_total_count] INT
,[diveloadleft_band3_total_pre_dive_load] INT
,[diveloadleft_band3_total_post_dive_load] INT
,[diveloadleft_band3_total_impact_dive_load] INT
,[diveloadright_band1_total_count] INT
,[diveloadright_band1_total_pre_dive_load] INT
,[diveloadright_band1_total_post_dive_load] INT
,[diveloadright_band1_total_impact_dive_load] INT
,[diveloadright_band2_total_count] INT
,[diveloadright_band2_total_pre_dive_load] INT
,[diveloadright_band2_total_post_dive_load] INT
,[diveloadright_band2_total_impact_dive_load] INT
,[diveloadright_band3_total_count] INT
,[diveloadright_band3_total_pre_dive_load] INT
,[diveloadright_band3_total_post_dive_load] INT
,[diveloadright_band3_total_impact_dive_load] INT
,[diveloadcentre_band1_total_count] INT
,[diveloadcentre_band1_total_pre_dive_load] INT
,[diveloadcentre_band1_total_post_dive_load] INT
,[diveloadcentre_band1_total_impact_dive_load] INT
,[diveloadcentre_band2_total_count] INT
,[diveloadcentre_band2_total_pre_dive_load] INT
,[diveloadcentre_band2_total_post_dive_load] INT
,[diveloadcentre_band2_total_impact_dive_load] INT
,[diveloadcentre_band3_total_count] INT
,[diveloadcentre_band3_total_pre_dive_load] INT
,[diveloadcentre_band3_total_post_dive_load] INT
,[diveloadcentre_band3_total_impact_dive_load] INT
,[timetofeetcentre_band1_total_count] INT
,[timetofeetcentre_band2_total_count] INT
,[timetofeetcentre_band3_total_count] INT
,[timetofeetleft_band1_total_count] INT
,[timetofeetleft_band2_total_count] INT
,[timetofeetleft_band3_total_count] INT
,[timetofeetright_band1_total_count] INT
,[timetofeetright_band2_total_count] INT
,[timetofeetright_band3_total_count] INT
,[gen2_acceleration_band1_total_distance] NUMERIC(10,5)
,[gen2_acceleration_band1_total_duration] NUMERIC(10,5)
,[gen2_acceleration_band1_total_effort_count] INT
,[gen2_acceleration_band2_total_distance] NUMERIC(10,5)
,[gen2_acceleration_band2_total_duration] NUMERIC(10,5)
,[gen2_acceleration_band2_total_effort_count] INT
,[gen2_acceleration_band3_total_distance] NUMERIC(10,5)
,[gen2_acceleration_band3_total_duration] NUMERIC(10,5)
,[gen2_acceleration_band3_total_effort_count] INT
,[gen2_acceleration_band6_total_distance] NUMERIC(10,5)
,[gen2_acceleration_band6_total_duration] NUMERIC(10,5)
,[gen2_acceleration_band6_total_effort_count] INT
,[gen2_acceleration_band7_total_distance] NUMERIC(10,5)
,[gen2_acceleration_band7_total_duration] NUMERIC(10,5)
,[gen2_acceleration_band7_total_effort_count] INT
,[gen2_acceleration_band8_total_distance] NUMERIC(10,5)
,[gen2_acceleration_band8_total_duration] NUMERIC(10,5)
,[gen2_acceleration_band8_total_effort_count] INT
,[ima_band1_accel_count] INT
,[ima_band1_right_count] INT
,[ima_band1_decel_count] INT
,[ima_band1_left_count] INT
,[ima_band1_direction1_count] INT
,[ima_band1_direction2_count] INT
,[ima_band1_direction3_count] INT
,[ima_band1_direction4_count] INT
,[ima_band1_direction5_count] INT
,[ima_band1_direction6_count] INT
,[ima_band1_direction7_count] INT
,[ima_band1_direction8_count] INT
,[ima_band1_direction9_count] INT
,[ima_band1_direction10_count] INT
,[ima_band1_direction11_count] INT
,[ima_band1_direction12_count] INT
,[ima_band1_jump_count] INT
,[imadiveintensityleft_band1_count] INT
,[imadiveintensityright_band1_count] INT
,[imadivereturnleft_band1_count] INT
,[imadivereturnright_band1_count] INT
,[imafreerunning_band1_total_duration] NUMERIC(10,5)
,[imafreerunning_band1_total_distance] NUMERIC(10,5)
,[imafreerunning_band1_total_player_load] INT
,[imadiveintensityleft_band1_return_band1_total_effort_count] INT
,[imadiveintensityright_band1_return_band1_total_effort_count] INT
,[imadiveintensityleft_band1_return_band2_total_effort_count] INT
,[imadiveintensityright_band1_return_band2_total_effort_count] INT
,[imadiveintensityleft_band1_return_band3_total_effort_count] INT
,[imadiveintensityright_band1_return_band3_total_effort_count] INT
,[imadiveintensityleft_band1_return_band4_total_effort_count] INT
,[imadiveintensityright_band1_return_band4_total_effort_count] INT
,[imadiveintensityleft_band1_return_band5_total_effort_count] INT
,[imadiveintensityright_band1_return_band5_total_effort_count] INT
,[imadiveintensityleft_band1_return_band6_total_effort_count] INT
,[imadiveintensityright_band1_return_band6_total_effort_count] INT
,[imadiveintensityleft_band1_return_band7_total_effort_count] INT
,[imadiveintensityright_band1_return_band7_total_effort_count] INT
,[imadiveintensityleft_band1_return_band8_total_effort_count] INT
,[imadiveintensityright_band1_return_band8_total_effort_count] INT
,[imaimpacts_band1_count] INT
,[ima_band2_accel_count] INT
,[ima_band2_right_count] INT
,[ima_band2_decel_count] INT
,[ima_band2_left_count] INT
,[ima_band2_direction1_count] INT
,[ima_band2_direction2_count] INT
,[ima_band2_direction3_count] INT
,[ima_band2_direction4_count] INT
,[ima_band2_direction5_count] INT
,[ima_band2_direction6_count] INT
,[ima_band2_direction7_count] INT
,[ima_band2_direction8_count] INT
,[ima_band2_direction9_count] INT
,[ima_band2_direction10_count] INT
,[ima_band2_direction11_count] INT
,[ima_band2_direction12_count] INT
,[ima_band2_jump_count] INT
,[imadiveintensityleft_band2_count] INT
,[imadiveintensityright_band2_count] INT
,[imadivereturnleft_band2_count] INT
,[imadivereturnright_band2_count] INT
,[imafreerunning_band2_total_duration] NUMERIC(10,5)
,[imafreerunning_band2_total_distance] NUMERIC(10,5)
,[imafreerunning_band2_total_player_load] INT
,[imadiveintensityleft_band2_return_band1_total_effort_count] INT
,[imadiveintensityright_band2_return_band1_total_effort_count] INT
,[imadiveintensityleft_band2_return_band2_total_effort_count] INT
,[imadiveintensityright_band2_return_band2_total_effort_count] INT
,[imadiveintensityleft_band2_return_band3_total_effort_count] INT
,[imadiveintensityright_band2_return_band3_total_effort_count] INT
,[imadiveintensityleft_band2_return_band4_total_effort_count] INT
,[imadiveintensityright_band2_return_band4_total_effort_count] INT
,[imadiveintensityleft_band2_return_band5_total_effort_count] INT
,[imadiveintensityright_band2_return_band5_total_effort_count] INT
,[imadiveintensityleft_band2_return_band6_total_effort_count] INT
,[imadiveintensityright_band2_return_band6_total_effort_count] INT
,[imadiveintensityleft_band2_return_band7_total_effort_count] INT
,[imadiveintensityright_band2_return_band7_total_effort_count] INT
,[imadiveintensityleft_band2_return_band8_total_effort_count] INT
,[imadiveintensityright_band2_return_band8_total_effort_count] INT
,[imaimpacts_band2_count] INT
,[ima_band3_accel_count] INT
,[ima_band3_right_count] INT
,[ima_band3_decel_count] INT
,[ima_band3_left_count] INT
,[ima_band3_direction1_count] INT
,[ima_band3_direction2_count] INT
,[ima_band3_direction3_count] INT
,[ima_band3_direction4_count] INT
,[ima_band3_direction5_count] INT
,[ima_band3_direction6_count] INT
,[ima_band3_direction7_count] INT
,[ima_band3_direction8_count] INT
,[ima_band3_direction9_count] INT
,[ima_band3_direction10_count] INT
,[ima_band3_direction11_count] INT
,[ima_band3_direction12_count] INT
,[ima_band3_jump_count] INT
,[imadiveintensityleft_band3_count] INT
,[imadiveintensityright_band3_count] INT
,[imadivereturnleft_band3_count] INT
,[imadivereturnright_band3_count] INT
,[imafreerunning_band3_total_duration] NUMERIC(10,5)
,[imafreerunning_band3_total_distance] NUMERIC(10,5)
,[imafreerunning_band3_total_player_load] INT
,[imadiveintensityleft_band3_return_band1_total_effort_count] INT
,[imadiveintensityright_band3_return_band1_total_effort_count] INT
,[imadiveintensityleft_band3_return_band2_total_effort_count] INT
,[imadiveintensityright_band3_return_band2_total_effort_count] INT
,[imadiveintensityleft_band3_return_band3_total_effort_count] INT
,[imadiveintensityright_band3_return_band3_total_effort_count] INT
,[imadiveintensityleft_band3_return_band4_total_effort_count] INT
,[imadiveintensityright_band3_return_band4_total_effort_count] INT
,[imadiveintensityleft_band3_return_band5_total_effort_count] INT
,[imadiveintensityright_band3_return_band5_total_effort_count] INT
,[imadiveintensityleft_band3_return_band6_total_effort_count] INT
,[imadiveintensityright_band3_return_band6_total_effort_count] INT
,[imadiveintensityleft_band3_return_band7_total_effort_count] INT
,[imadiveintensityright_band3_return_band7_total_effort_count] INT
,[imadiveintensityleft_band3_return_band8_total_effort_count] INT
,[imadiveintensityright_band3_return_band8_total_effort_count] INT
,[imaimpacts_band3_count] INT
,[ima_band4_jump_count] INT
,[imadiveintensityleft_band4_count] INT
,[imadiveintensityright_band4_count] INT
,[imadivereturnleft_band4_count] INT
,[imadivereturnright_band4_count] INT
,[imafreerunning_band4_total_duration] NUMERIC(10,5)
,[imafreerunning_band4_total_distance] NUMERIC(10,5)
,[imafreerunning_band4_total_player_load] INT
,[imadiveintensityleft_band4_return_band1_total_effort_count] INT
,[imadiveintensityright_band4_return_band1_total_effort_count] INT
,[imadiveintensityleft_band4_return_band2_total_effort_count] INT
,[imadiveintensityright_band4_return_band2_total_effort_count] INT
,[imadiveintensityleft_band4_return_band3_total_effort_count] INT
,[imadiveintensityright_band4_return_band3_total_effort_count] INT
,[imadiveintensityleft_band4_return_band4_total_effort_count] INT
,[imadiveintensityright_band4_return_band4_total_effort_count] INT
,[imadiveintensityleft_band4_return_band5_total_effort_count] INT
,[imadiveintensityright_band4_return_band5_total_effort_count] INT
,[imadiveintensityleft_band4_return_band6_total_effort_count] INT
,[imadiveintensityright_band4_return_band6_total_effort_count] INT
,[imadiveintensityleft_band4_return_band7_total_effort_count] INT
,[imadiveintensityright_band4_return_band7_total_effort_count] INT
,[imadiveintensityleft_band4_return_band8_total_effort_count] INT
,[imadiveintensityright_band4_return_band8_total_effort_count] INT
,[imaimpacts_band4_count] INT
,[ima_band5_jump_count] INT
,[imadiveintensityleft_band5_count] INT
,[imadiveintensityright_band5_count] INT
,[imadivereturnleft_band5_count] INT
,[imadivereturnright_band5_count] INT
,[imafreerunning_band5_total_duration] NUMERIC(10,5)
,[imafreerunning_band5_total_distance] NUMERIC(10,5)
,[imafreerunning_band5_total_player_load] INT
,[imadiveintensityleft_band5_return_band1_total_effort_count] INT
,[imadiveintensityright_band5_return_band1_total_effort_count] INT
,[imadiveintensityleft_band5_return_band2_total_effort_count] INT
,[imadiveintensityright_band5_return_band2_total_effort_count] INT
,[imadiveintensityleft_band5_return_band3_total_effort_count] INT
,[imadiveintensityright_band5_return_band3_total_effort_count] INT
,[imadiveintensityleft_band5_return_band4_total_effort_count] INT
,[imadiveintensityright_band5_return_band4_total_effort_count] INT
,[imadiveintensityleft_band5_return_band5_total_effort_count] INT
,[imadiveintensityright_band5_return_band5_total_effort_count] INT
,[imadiveintensityleft_band5_return_band6_total_effort_count] INT
,[imadiveintensityright_band5_return_band6_total_effort_count] INT
,[imadiveintensityleft_band5_return_band7_total_effort_count] INT
,[imadiveintensityright_band5_return_band7_total_effort_count] INT
,[imadiveintensityleft_band5_return_band8_total_effort_count] INT
,[imadiveintensityright_band5_return_band8_total_effort_count] INT
,[imaimpacts_band5_count] INT
,[ima_band6_jump_count] INT
,[imadiveintensityleft_band6_count] INT
,[imadiveintensityright_band6_count] INT
,[imadivereturnleft_band6_count] INT
,[imadivereturnright_band6_count] INT
,[imafreerunning_band6_total_duration] NUMERIC(10,5)
,[imafreerunning_band6_total_distance] NUMERIC(10,5)
,[imafreerunning_band6_total_player_load] INT
,[imadiveintensityleft_band6_return_band1_total_effort_count] INT
,[imadiveintensityright_band6_return_band1_total_effort_count] INT
,[imadiveintensityleft_band6_return_band2_total_effort_count] INT
,[imadiveintensityright_band6_return_band2_total_effort_count] INT
,[imadiveintensityleft_band6_return_band3_total_effort_count] INT
,[imadiveintensityright_band6_return_band3_total_effort_count] INT
,[imadiveintensityleft_band6_return_band4_total_effort_count] INT
,[imadiveintensityright_band6_return_band4_total_effort_count] INT
,[imadiveintensityleft_band6_return_band5_total_effort_count] INT
,[imadiveintensityright_band6_return_band5_total_effort_count] INT
,[imadiveintensityleft_band6_return_band6_total_effort_count] INT
,[imadiveintensityright_band6_return_band6_total_effort_count] INT
,[imadiveintensityleft_band6_return_band7_total_effort_count] INT
,[imadiveintensityright_band6_return_band7_total_effort_count] INT
,[imadiveintensityleft_band6_return_band8_total_effort_count] INT
,[imadiveintensityright_band6_return_band8_total_effort_count] INT
,[imaimpacts_band6_count] INT
,[ima_band7_jump_count] INT
,[imadiveintensityleft_band7_count] INT
,[imadiveintensityright_band7_count] INT
,[imadivereturnleft_band7_count] INT
,[imadivereturnright_band7_count] INT
,[imafreerunning_band7_total_duration] NUMERIC(10,5)
,[imafreerunning_band7_total_distance] NUMERIC(10,5)
,[imafreerunning_band7_total_player_load] INT
,[imadiveintensityleft_band7_return_band1_total_effort_count] INT
,[imadiveintensityright_band7_return_band1_total_effort_count] INT
,[imadiveintensityleft_band7_return_band2_total_effort_count] INT
,[imadiveintensityright_band7_return_band2_total_effort_count] INT
,[imadiveintensityleft_band7_return_band3_total_effort_count] INT
,[imadiveintensityright_band7_return_band3_total_effort_count] INT
,[imadiveintensityleft_band7_return_band4_total_effort_count] INT
,[imadiveintensityright_band7_return_band4_total_effort_count] INT
,[imadiveintensityleft_band7_return_band5_total_effort_count] INT
,[imadiveintensityright_band7_return_band5_total_effort_count] INT
,[imadiveintensityleft_band7_return_band6_total_effort_count] INT
,[imadiveintensityright_band7_return_band6_total_effort_count] INT
,[imadiveintensityleft_band7_return_band7_total_effort_count] INT
,[imadiveintensityright_band7_return_band7_total_effort_count] INT
,[imadiveintensityleft_band7_return_band8_total_effort_count] INT
,[imadiveintensityright_band7_return_band8_total_effort_count] INT
,[imaimpacts_band7_count] INT
,[ima_band8_right_count] INT
,[ima_band8_left_count] INT
,[ima_band8_jump_count] INT
,[imadiveintensityleft_band8_count] INT
,[imadiveintensityright_band8_count] INT
,[imadivereturnleft_band8_count] INT
,[imadivereturnright_band8_count] INT
,[imafreerunning_band8_total_duration] NUMERIC(10,5)
,[imafreerunning_band8_total_distance] NUMERIC(10,5)
,[imafreerunning_band8_total_player_load] INT
,[imadiveintensityleft_band8_return_band1_total_effort_count] INT
,[imadiveintensityright_band8_return_band1_total_effort_count] INT
,[imadiveintensityleft_band8_return_band2_total_effort_count] INT
,[imadiveintensityright_band8_return_band2_total_effort_count] INT
,[imadiveintensityleft_band8_return_band3_total_effort_count] INT
,[imadiveintensityright_band8_return_band3_total_effort_count] INT
,[imadiveintensityleft_band8_return_band4_total_effort_count] INT
,[imadiveintensityright_band8_return_band4_total_effort_count] INT
,[imadiveintensityleft_band8_return_band5_total_effort_count] INT
,[imadiveintensityright_band8_return_band5_total_effort_count] INT
,[imadiveintensityleft_band8_return_band6_total_effort_count] INT
,[imadiveintensityright_band8_return_band6_total_effort_count] INT
,[imadiveintensityleft_band8_return_band7_total_effort_count] INT
,[imadiveintensityright_band8_return_band7_total_effort_count] INT
,[imadiveintensityleft_band8_return_band8_total_effort_count] INT
,[imadiveintensityright_band8_return_band8_total_effort_count] INT
,[imaimpacts_band8_count] INT
,[ima_v1_free_run_events] INT
,[ima_v1_free_run_duration] INT
,[ima_v2_free_run_events] INT
,[ima_v2_free_run_duration] INT
,[ima_v1_free_run_band1_event_count] INT
,[ima_v2_free_run_band1_event_count] INT
,[ima_v2_free_run_band1_total_strides] INT
,[ima_v1_free_run_band2_event_count] INT
,[ima_v2_free_run_band2_event_count] INT
,[ima_v2_free_run_band2_total_strides] INT
,[ima_v1_free_run_band3_event_count] INT
,[ima_v2_free_run_band3_event_count] INT
,[ima_v2_free_run_band3_total_strides] INT
,[ima_v1_free_run_band4_event_count] INT
,[ima_v2_free_run_band4_event_count] INT
,[ima_v2_free_run_band4_total_strides] INT
,[ima_v1_free_run_band5_event_count] INT
,[ima_v2_free_run_band5_event_count] INT
,[ima_v2_free_run_band5_total_strides] INT
,[ima_v1_free_run_band6_event_count] INT
,[ima_v2_free_run_band6_event_count] INT
,[ima_v2_free_run_band6_total_strides] INT
,[ima_v1_free_run_band7_event_count] INT
,[ima_v2_free_run_band7_event_count] INT
,[ima_v2_free_run_band7_total_strides] INT
,[ima_v1_free_run_band8_event_count] INT
,[ima_v2_free_run_band8_event_count] INT
,[ima_v2_free_run_band8_total_strides] INT
,[rhie_bout_count] INT
,[rhie_min_effort_duration] NUMERIC(10,5)
,[rhie_max_effort_duration] NUMERIC(10,5)
,[rhie_min_effort_count] INT
,[rhie_max_effort_count] INT
,[rhie_min_effort_recovery] INT
,[rhie_max_effort_recovery] INT
,[rhie_min_bout_recovery] INT
,[rhie_max_bout_recovery] INT
,[max_intensity_interval_distance_interval_1] NVARCHAR(100)
,[max_intensity_interval_dist_interval_1_start_time] NVARCHAR(100)
,[max_intensity_interval_dist_interval_1_end_time] NVARCHAR(100)
,[max_intensity_interval_distance_interval_2] NVARCHAR(100)
,[max_intensity_interval_dist_interval_2_start_time] NVARCHAR(100)
,[max_intensity_interval_dist_interval_2_end_time] NVARCHAR(100)
,[max_intensity_interval_distance_interval_3] NVARCHAR(100)
,[max_intensity_interval_dist_interval_3_start_time] NVARCHAR(100)
,[max_intensity_interval_dist_interval_3_end_time] NVARCHAR(100)
,[max_intensity_interval_player_load_interval_1] NVARCHAR(100)
,[max_intensity_interval_pl_interval_1_start_time] NVARCHAR(100)
,[max_intensity_interval_pl_interval_1_end_time] NVARCHAR(100)
,[max_intensity_interval_player_load_interval_2] NVARCHAR(100)
,[max_intensity_interval_pl_interval_2_start_time] NVARCHAR(100)
,[max_intensity_interval_pl_interval_2_end_time] NVARCHAR(100)
,[max_intensity_interval_player_load_interval_3] NVARCHAR(100)
,[max_intensity_interval_pl_interval_3_start_time] NVARCHAR(100)
,[max_intensity_interval_pl_interval_3_end_time] NVARCHAR(100)
,[total_ima__per__perc] INT
,[average_verticaljump] INT
,[asd] NUMERIC(20,16)
,[osszido] INT
,[nagy_intenzitasu_iranyvaltasok_balra_(-)] INT
,[iranyvaltasok_2d_sum] INT
,[tot_acc_ima_(band1-3)] INT
,[alacsony_intenzitasu_lassulas_(-)] NVARCHAR(100)
,[25_km_per_h_feletti_(m)] INT
,[number_of_decelerations_>-3_m_per_s2_per_minute] NUMERIC(20,17)
,[gen2_acceleration_band2plus_average_effort_count] INT
,[hsr_per___(m_per_min)] NUMERIC(20,17)
,[dec_high__per__perc] NUMERIC(20,17)
,[proba_parameter] NVARCHAR(100)
,[tot_decel_ima_(band1-3)] INT
,[acceleration_density] NUMERIC(20,16)
,[accel_load_density_index] NUMERIC(10,6)
,[playerload__per__perc] NUMERIC(10,5)
,[hsr_+_sprint_(>19,8km_per_h)_(m)] NUMERIC(10,5)
,[number_of_accelerations_>3_m_per_s2] INT
,[gen2_acceleration_band7plus_average_effort_count] INT
,[high_metabolic_power_efforts] INT
,[30km_per_h_folotti_futas_megtett_tav] INT
,[rpe] INT
,[total_right_dives] INT
,[lowerbodysoreness] INT
,[sprinttesting] INT
,[start_time_h] NVARCHAR(50)
,[end_time_h] NVARCHAR(50)
,[maxpulzus_85-105%_megtett_tav%] INT
,[magas_intenzitasu_+_sprint_futas_(>19,8_km_per_h)_per_perc] NUMERIC(20,18)
,[1rmdeadlift] INT
,[ima_dec_low_per__session] INT
,[ima_decel_low] INT
,[running_footstrikes] INT
,[running_imbalance] NUMERIC(20,15)
,[running_deviation] NUMERIC(10,5)
,[kozepes_futas_megtett_tav_per_eltelt_ido] NUMERIC(20,16)
,[hr?90%] INT
,[sprint_futasok_szama] NVARCHAR(100)
,[average_1rmsquat] INT
,[aktiv_%] NVARCHAR(100)
,[number_of_decelerations_>-3_m_per_s2] NVARCHAR(100)
,[average_1rmbenchpull] INT
,[explosive_efforts] INT
,[magas_intenzitasu_+_sprint_futas_(>19,8_km_per_h)_(m)] NUMERIC(10,5)
,[anaerob_zonaban_toltott_edzesido%] INT
,[average_sprinttesting] INT
,[average_1rmbenchpress] INT
,[1rmsquat] INT
,[average_rpe] INT
,[lassitas__per__perc] INT
,[zone_2_lassulasi_esemenyek_per_eltelt_ido] NUMERIC(20,16)
,[average_upperbodysoreness] INT
,[alacsony_intenzitasu_iranyvaltasok_balra_(-)] INT
,[ima_dec_<2,5_per_session_per_min] NUMERIC(20,16)
,[tot_ima_high_(db)] INT
,[attila_proba_teszt] INT
,[sprint_futas_megtett_tav_per_eltelt_ido] NVARCHAR(100)
,[kozepes_intenzitasu_iranyvaltasok_balra_(-)] INT
,[aktiv_ido] NUMERIC(20,15)
,[diveloadright_band1_average_pre_dive_load] INT
,[diveloadright_band2_average_pre_dive_load] INT
,[diveloadright_band3_average_pre_dive_load] INT
,[diveloadright_band1_average_impact_dive_load] INT
,[diveloadright_band2_average_impact_dive_load] INT
,[diveloadright_band3_average_impact_dive_load] INT
,[diveloadright_band1_average_post_dive_load] INT
,[diveloadright_band2_average_post_dive_load] INT
,[diveloadright_band3_average_post_dive_load] INT
,[diveloadleft_band1_average_pre_dive_load] INT
,[diveloadleft_band2_average_pre_dive_load] INT
,[diveloadleft_band3_average_pre_dive_load] INT
,[diveloadleft_band1_average_impact_dive_load] INT
,[diveloadleft_band2_average_impact_dive_load] INT
,[diveloadleft_band3_average_impact_dive_load] INT
,[diveloadleft_band1_average_post_dive_load] INT
,[diveloadleft_band2_average_post_dive_load] INT
,[diveloadleft_band3_average_post_dive_load] INT
,[diveloadcentre_band1_average_pre_dive_load] INT
,[diveloadcentre_band2_average_pre_dive_load] INT
,[diveloadcentre_band3_average_pre_dive_load] INT
,[diveloadcentre_band1_average_impact_dive_load] INT
,[diveloadcentre_band2_average_impact_dive_load] INT
,[diveloadcentre_band3_average_impact_dive_load] INT
,[diveloadcentre_band1_average_post_dive_load] INT
,[diveloadcentre_band2_average_post_dive_load] INT
,[diveloadcentre_band3_average_post_dive_load] INT
,[average_time_to_feeet_left] NVARCHAR(100)
,[average_time_to_feeet_right] NVARCHAR(100)
,[average_time_to_feet_centre] NVARCHAR(100)
,[average_goalkeeping_dives] INT
,[total_dive_load_low_intensity] INT
,[total_dive_load_med_intensity] INT
,[total_dive_load_high_intensity] INT
,[total_dive_load_right_low_intensity] INT
,[total_dive_load_right_med_intensity] INT
,[total_dive_load_right_high_intensity] INT
,[total_dive_load_left_low_intensity] INT
,[total_dive_load_left_med_intensity] INT
,[total_dive_load_left_high_intensity] INT
,[total_dive_load_centre_low_intensity] INT
,[total_dive_load_centre_med_intensity] INT
,[total_dive_load_centre_high_intensity] INT
,[average_dive_load_low_intensity_session] INT
,[average_dive_load_med_intensity_session] INT
,[average_dive_load_high_intensity_session] INT
,[average_dive_load_right_low_intensity_session] INT
,[average_dive_load_right_med_intensity_session] INT
,[average_dive_load_right_high_intensity_session] INT
,[average_dive_load_left_low_intensity_session] INT
,[average_dive_load_left_med_intensity_session] INT
,[average_dive_load_left_high_intensity_session] INT
,[average_dive_load_centre_low_intensity_session] INT
,[average_dive_load_centre_med_intensity_session] INT
,[average_dive_load_centre_high_intensity_session] INT
,[30km_per_h_folotti_futasok_szama_per_eltlet_ido] NVARCHAR(100)
,[sleepquality] INT
,[explosive_distance_±2_m_per_s2_per_minute] NUMERIC(20,16)
,[gen2_acceleration_band3plus_total_distance] NUMERIC(10,5)
,[gen2_acceleration_band6plus_total_distance] NUMERIC(10,5)
,[iranyvaltasok_2d_sum_per_perc] NUMERIC(20,15)
,[acc_high__per__perc] NUMERIC(20,17)
,[average_weight] INT
,[ima_acc_<2,5_per_session_per_min] NUMERIC(20,17)
,[magas_intenzitasu_futas_19,8-25,2_km_per_h_(m)__per__perc] INT
,[avg_-_aktiv%] NVARCHAR(100)
,[megtett_tav__per__perc] NUMERIC(10,5)
,[edwards_trimp] NVARCHAR(100)
,[maxpulzus_85-105%_megtett_tav_%] INT
,[maxpulzus_85-105%_edzesido_%] INT
,[total_jumps] INT
,[kozepes_futasok_szama] INT
,[zone_3_gyorsulasi_esemenyek_per_eltelt_ido] NVARCHAR(100)
,[ossztav] NUMERIC(10,5)
,[total_ima_events_high_(total)_new_(db)] INT
,[gen2_acceleration_band3plus_total_effort_count] INT
,[gen2_acceleration_band2plus_total_effort_count] INT
,[gen2_acceleration_band6plus_total_effort_count] INT
,[gen2_acceleration_band7plus_total_effort_count] INT
,[gen2_acceleration_band3_average_effort_count_session] INT
,[gen2_acceleration_band2_average_effort_count_session] INT
,[gen2_acceleration_band1_average_effort_count_session] INT
,[gen2_acceleration_band6_average_effort_count_session] INT
,[gen2_acceleration_band7_average_effort_count_session] INT
,[gen2_acceleration_band8_average_effort_count_session] INT
,[gen2_acceleration_band3plus_average_effort_count] INT
,[gen2_acceleration_band6plus_average_effort_count] INT
,[gen2_acceleration_band3plus_total_duration] NUMERIC(20,17)
,[gen2_acceleration_band2plus_total_duration] NUMERIC(10,5)
,[gen2_acceleration_band6plus_total_duration] NUMERIC(10,5)
,[gen2_acceleration_band7plus_total_duration] NUMERIC(10,5)
,[gen2_acceleration_band2plus_total_distance] NUMERIC(10,5)
,[gen2_acceleration_band7plus_total_distance] NUMERIC(10,5)
,[average_gnss_quality] NUMERIC(20,12)
,[average_hdop] NUMERIC(20,16)
,[average_satellite_count] NUMERIC(20,15)
,[lok_-_terjedelem_%] NUMERIC(20,16)
,[passziv_%] NVARCHAR(100)
,[atila] INT
,[iranyvaltasok_2d_b3_(gen2)] INT
,[avg_-_passziv_%] NVARCHAR(100)
,[magas_intenzitasu_futas_megtett_tav] INT
,[zone_1_gyorsulasi_esemenyek_per_eltelt_ido] NUMERIC(20,15)
,[ima_per_gps_tav] NUMERIC(10,5)
,[lassulasi_esemenyek_per_eltelt_ido] NUMERIC(20,16)
,[acceleration_load_average] NUMERIC(10,5)
,[kozepes_futasok_szama_per_eltelt_ido] NVARCHAR(100)
,[osszes_ima] INT
,[gyorsulasi_esemenyek_per_eltelt_ido] NUMERIC(20,17)
,[hr_per_perc] INT
,[magas_intenzitasu_futas_megtett_tav_per_eltelt_ido] NUMERIC(20,15)
,[acc_high_per__session] INT
,[szorzo] INT
,[high_acc_per_dec_vizsga] NVARCHAR(100)
,[hr_index__per__edzes_(sulyozott_pulzusteljesitmeny)] INT
,[iranyvaltasok_2d_3] INT
,[gyorsulas_b2-3__per__perc] NUMERIC(20,17)
,[date] date
,[average_lowerbodysoreness] INT
,[total_dives] INT
,[sprint_futasok_atlagos_hossza] INT
,[average_2d_player_load] INT
,[max_sebesseg] NUMERIC(10,5)
,[magas_intenzitasu_futasok_szama_per_eltelt_ido] NVARCHAR(100)
,[imadivereturnleft_band1_average_recovery] INT
,[imadivereturnright_band1_average_recovery] INT
,[imadivereturnleft_band2_average_recovery] INT
,[imadivereturnright_band2_average_recovery] INT
,[30km_per_h_folotti_futasok_szama] INT
,[imadivereturnleft_band3_average_recovery] INT
,[imadivereturnright_band3_average_recovery] INT
,[imadivereturnleft_band4_average_recovery] INT
,[imadivereturnright_band4_average_recovery] INT
,[imadivereturnleft_band5_average_recovery] INT
,[imadivereturnright_band5_average_recovery] INT
,[imadivereturnleft_band6_average_recovery] INT
,[imadivereturnright_band6_average_recovery] INT
,[imadivereturnleft_band7_average_recovery] INT
,[imadivereturnright_band7_average_recovery] INT
,[imadivereturnleft_band8_average_recovery] INT
,[imadivereturnright_band8_average_recovery] INT
,[fmp_-_total_duration] NVARCHAR(100)
,[average_1rmdeadlift] INT
,[peakpower] INT
,[nagy_intenzitasu_lassulas_(-)] NVARCHAR(100)
,[iranyvaltasok_2d_3_per_perc] NUMERIC(20,17)
,[average_aerobictesting] INT
,[mech_-_terjedelem] NUMERIC(12,6)
,[lassulas_b2-+__per__perc] NUMERIC(12,6)
,[kozepes_futasok_atlagos_hossza] NUMERIC(10,5)
,[zone_3_lassulasi_esemenyek_per_eltelt_ido] NVARCHAR(100)
,[average_peakpower] INT
,[osszes_ima__per__perc] NUMERIC(20,15)
,[sprint_>25km_per_h__per__perc] INT
,[sprint_futas_25,2_km_per_h_felett_(m)] INT
,[weight] INT
,[iranyvaltasok_2d_2+_per_perc] NUMERIC(20,16)
,[zone_2_gyorsulasi_esemenyek_per_eltelt_ido] NUMERIC(20,17)
,[velocity_band5+_per_perc] INT
,[sprint_per__min_(<25,2_km_per_h_)] INT
)