CREATE TABLE input_catapult_stats_2 ( load_timestamp DATETIME DEFAULT GETDATE()
,[athlete_id] NVARCHAR(100)
--,[osszes_ima__per__perc] numeric(10,5)
--,[sprint_>25km_per_h__per__perc] int
--,[sprint_futas_25,2_km_per_h_felett_(m)] int
--,[weight] int
--,[iranyvaltasok_2d_2+_per_perc] numeric(20,16)
--,[zone_2_gyorsulasi_esemenyek_per_eltelt_ido] numeric(20,17)
--,[velocity_band5+_per_perc] int
--,[sprint_per__min_(<25,2_km_per_h_)] int



,[iranyvaltasok_2d_1] int
,[verticaljump] NVARCHAR(100)
,[robbanekony_akciok_per_] numeric(20,17)
,[tot_ima_high_(db)_per_min] numeric(20,17)
,[iranyvaltasok_2d_2] int
,[robbanekony_akciok__per__perc] numeric(20,17)
,[number_of_accelerations_>3_m_per_s2_per_minute] numeric(20,17)
,[1rmbenchpress] int
,[equivalent_distance_per_minute] numeric(20,14)
,[zone_1_lassulasi_esemenyek_per_eltelt_ido] numeric(20,14)
,[imafreerunning_band1_player_load_per_minute] nvarchar(100)
,[imafreerunning_band1_ima_v2_free_run_duration] int
,[imafreerunning_band2_player_load_per_minute] nvarchar(100)
,[imafreerunning_band2_ima_v2_free_run_duration] int
,[imafreerunning_band3_player_load_per_minute] nvarchar(100)
,[imafreerunning_band3_ima_v2_free_run_duration] int
,[imafreerunning_band4_player_load_per_minute] nvarchar(100)
,[imafreerunning_band4_ima_v2_free_run_duration] int
,[imafreerunning_band5_player_load_per_minute] nvarchar(100)
,[imafreerunning_band5_ima_v2_free_run_duration] int
,[imafreerunning_band6_player_load_per_minute] nvarchar(100)
,[imafreerunning_band6_ima_v2_free_run_duration] int
,[imafreerunning_band7_player_load_per_minute] nvarchar(100)
,[imafreerunning_band7_ima_v2_free_run_duration] int
,[imafreerunning_band8_player_load_per_minute] nvarchar(100)
,[imafreerunning_band8_ima_v2_free_run_duration] int
,[time_>85%_hrmax] int
,[felugrasok_szama_(20-60_cm)_(db)] int
,[ossz_felugrasok_szama_(0-60_cm)_(db)] NVARCHAR(100)
,[kozepes_intenzitasu_lassulas_(db)] int
,[edi_per_perc] numeric(20,17)
,[kozepes_intenzitasu_futas_14,4-19,8_km_per_h_(m)__per__perc] numeric(20,17)
,[explosive_distance_±2_m_per_s2] numeric(10,2)
,[edwards_trimp_per_minute] int
,[ima_dec_<2,5_per_session] int
,[robbanekony_akciok_per_perc] nvarchar(100)
,[szorz] int
,[metapower_>25,5_w_per_kg] numeric(10,2)
,[ima_acc_<2,5_per_session] int
,[passziv_ido] numeric(10,5)
,[aerobictesting] int
,[maxpulzus_85-105%_edzesido%] int
,[metapower_>25,5_w_per_kg__per__perc] numeric(20,17)
,[upperbodysoreness] int
,[30km_per_h_folotti_futasok_atlagos_hossza] int
,[sprint_futas_megtett_tav] int
,[1rmbenchpull] int
,[average_sleepquality] int
,[magas_intenzitasu_futasok_szama] int
,[hsr_+_sprint_(>19,8km_per_h)_per_minute] numeric(20,17)
,[sprint_eng] int
,[total_left_dives] int
,[athlete_max_hr] int
,[athlete_max_velocity] numeric(10,2)
,[ima_band1_old_accel_count] int
,[ima_band1_old_right_count] int
,[ima_band1_old_decel_count] int
,[ima_band1_old_left_count] int
,[ima_band1_old_direction1_count] int
,[ima_band1_old_direction2_count] int
,[ima_band1_old_direction3_count] int
,[ima_band1_old_direction4_count] int
,[ima_band1_old_direction5_count] int
,[ima_band1_old_direction6_count] int
,[ima_band1_old_direction7_count] int
,[ima_band1_old_direction8_count] int
,[ima_band1_old_direction9_count] int
,[ima_band1_old_direction10_count] int
,[ima_band1_old_direction11_count] int
,[ima_band1_old_direction12_count] int
,[ima_band2_old_accel_count] int
,[ima_band2_old_right_count] int
,[ima_band2_old_decel_count] int
,[ima_band2_old_left_count] int
,[ima_band2_old_direction1_count] int
,[ima_band2_old_direction2_count] int
,[ima_band2_old_direction3_count] int
,[ima_band2_old_direction4_count] int
,[ima_band2_old_direction5_count] int
,[ima_band2_old_direction6_count] int
,[ima_band2_old_direction7_count] int
,[ima_band2_old_direction8_count] int
,[ima_band2_old_direction9_count] int
,[ima_band2_old_direction10_count] int
,[ima_band2_old_direction11_count] int
,[ima_band2_old_direction12_count] int
,[ima_band3_old_accel_count] int
,[ima_band3_old_right_count] int
,[ima_band3_old_decel_count] int
,[ima_band3_old_left_count] int
,[ima_band3_old_direction1_count] int
,[ima_band3_old_direction2_count] int
,[ima_band3_old_direction3_count] int
,[ima_band3_old_direction4_count] int
,[ima_band3_old_direction5_count] int
,[ima_band3_old_direction6_count] int
,[ima_band3_old_direction7_count] int
,[ima_band3_old_direction8_count] int
,[ima_band3_old_direction9_count] int
,[ima_band3_old_direction10_count] int
,[ima_band3_old_direction11_count] int
,[ima_band3_old_direction12_count] int
,[ima_band8_old_right_count] int
,[ima_band8_old_left_count] int
,[activity_count] int
,[total_activities] int
,[meta_energy_kj] numeric(10,5)
,[meta_energy_cal] numeric(10,5)
,[vel_work_rest_ratio] numeric(10,5)
,[work_rest_ratio] numeric(10,5)
,[velocity_band5_total_effort_count_for_average] int
,[velocity_band6_total_effort_count_for_average] int
,[velocity_band7_total_effort_count_for_average] int
,[velocity_band8_total_effort_count_for_average] int
,[average_duration] numeric(10,5)
,[average_distance] numeric(10,5)
,[average_player_load] numeric(10,5)
,[mean_heart_rate] int
,[average_slow_player_load] numeric(10,5)
,[average_1d_fwd_player_load] numeric(10,5)
,[average_1d_side_player_load] numeric(10,5)
,[average_1d_up_player_load] numeric(10,5)
,[player_load_per_metre] numeric(10,5)
,[player_load_per_minute] numeric(10,5)
,[meterage_per_minute] numeric(10,5)
,[velocity_exertion_per_minute] numeric(10,5)
,[heart_rate_exertion_per_minute] int
,[heart_rate_exertion_per_metre] int
,[equivalent_distance_index] numeric(10,5)
,[average_duration_session] int
,[average_distance_session] numeric(10,5)
,[average_player_load_session] numeric(10,5)
,[average_2d_player_load_session] numeric(10,5)
,[average_slow_player_load_session] numeric(10,5)
,[average_1d_fwd_player_load_session] numeric(10,5)
,[average_1d_side_player_load_session] numeric(10,5)
,[average_1d_up_player_load_session] numeric(10,5)
,[1d_fwd_player_load_percentage] numeric(10,5)
,[1d_side_player_load_percentage] numeric(10,5)
,[1d_up_player_load_percentage] numeric(10,5)
,[percentage_avg_heart_rate] int
,[percentage_max_heart_rate] int
,[average_velocity] numeric(10,5)
,[percentage_max_velocity] numeric(10,5)
,[dive_load_per_minute] int
,[average_time_to_feet] int
,[fmp_very_low_duration_average] numeric(10,5)
,[fmp_low_duration_average] int
,[fmp_running_med_duration_average] int
,[fmp_running_high_duration_average] int
,[fmp_running_total_duration_average] int
,[fmp_dynamic_med_duration_average] numeric(10,5)
,[fmp_dynamic_high_duration_average] int
,[fmp_dynamic_total_duration_average] int
,[fmp_very_low_duration_percentage] numeric(10,5)
,[fmp_low_duration_percentage] numeric(10,5)
,[fmp_running_med_duration_percentage] numeric(10,5)
,[fmp_running_high_duration_percentage] numeric(10,5)
,[fmp_running_total_duration_percentage] numeric(10,5)
,[fmp_dynamic_med_duration_percentage] numeric(10,5)
,[fmp_dynamic_high_duration_percentage] numeric(10,5)
,[fmp_dynamic_total_duration_percentage] numeric(10,5)
,[velocity_band1_average_distance] numeric(10,2)
,[velocity_band1_average_duration] numeric(10,5)
,[velocity_band1_average_distance_session] numeric(10,2)
,[velocity_band1_average_duration_session] numeric(10,5)
,[velocity_band1_distance_percentage] numeric(10,5)
,[velocity_band1_duration_percentage] numeric(10,5)
,[velocity_band2_average_distance] numeric(10,5)
,[velocity_band2_average_duration] numeric(10,1)
,[velocity_band2_average_effort_count] int
,[velocity_band2_average_distance_session] numeric(10,5)
,[velocity_band2_average_duration_session] numeric(10,1)
,[velocity_band2_average_effort_count_session] int
,[velocity_band2_distance_percentage] numeric(10,5)
,[velocity_band2_duration_percentage] numeric(10,5)
,[velocity_band2_average_effort_distance] int
,[velocity_band2_average_effort_duration] int
,[velocity_band3_average_distance] numeric(10,5)
,[velocity_band3_average_duration] numeric(10,5)
,[velocity_band3_average_effort_count] int
,[velocity_band3_average_distance_session] numeric(10,5)
,[velocity_band3_average_duration_session] numeric(10,1)
,[velocity_band3_average_effort_count_session] int
,[velocity_band3_distance_percentage] numeric(10,5)
,[velocity_band3_duration_percentage] numeric(10,5)
,[velocity_band3_average_effort_distance] int
,[velocity_band3_average_effort_duration] int
,[velocity_band4_average_distance] numeric(10,5)
,[velocity_band4_average_duration] numeric(10,5)
,[velocity_band4_average_effort_count] int
,[velocity_band4_average_distance_session] numeric(10,5)
,[velocity_band4_average_duration_session] numeric(10,5)
,[velocity_band4_average_effort_count_session] int
,[velocity_band4_distance_percentage] numeric(10,5)
,[velocity_band4_duration_percentage] numeric(10,5)
,[velocity_band4_average_effort_distance] numeric(10,5)
,[velocity_band4_average_effort_duration] numeric(10,5)
,[velocity_band5_average_distance] numeric(10,5)
,[velocity_band5_average_duration] numeric(10,5)
,[velocity_band5_average_effort_count] int
,[velocity_band5_average_distance_session] numeric(10,5)
,[velocity_band5_average_duration_session] numeric(10,5)
,[velocity_band5_average_effort_count_session] numeric(10,5)
,[velocity_band5_distance_percentage] numeric(10,5)
,[velocity_band5_duration_percentage] numeric(10,5)
,[velocity_band5_average_effort_distance] numeric(10,5)
,[velocity_band5_average_effort_duration] numeric(10,5)
,[velocity_band6_average_distance] numeric(10,5)
,[velocity_band6_average_duration] numeric(10,5)
,[velocity_band6_average_effort_count] int
,[velocity_band6_average_distance_session] numeric(10,5)
,[velocity_band6_average_duration_session] numeric(10,5)
,[velocity_band6_average_effort_count_session] numeric(10,5)
,[velocity_band6_distance_percentage] numeric(10,5)
,[velocity_band6_duration_percentage] numeric(10,5)
,[velocity_band6_average_effort_distance] numeric(10,5)
,[velocity_band6_average_effort_duration] numeric(10,5)
,[velocity_band7_average_distance] numeric(10,5)
,[velocity_band7_average_duration] numeric(10,5)
,[velocity_band7_average_effort_count] int
,[velocity_band7_average_distance_session] numeric(10,5)
,[velocity_band7_average_duration_session] numeric(10,5)
,[velocity_band7_average_effort_count_session] numeric(10,5)
,[velocity_band7_distance_percentage] numeric(10,5)
,[velocity_band7_duration_percentage] numeric(10,5)
,[velocity_band7_average_effort_distance] numeric(10,5)
,[velocity_band7_average_effort_duration] numeric(10,5)
,[velocity_band8_average_distance] numeric(10,5)
,[velocity_band8_average_duration] numeric(10,5)
,[velocity_band8_average_effort_count] int
,[velocity_band8_average_distance_session] numeric(10,5)
,[velocity_band8_average_duration_session] numeric(10,5)
,[velocity_band8_average_effort_count_session] numeric(10,5)
,[velocity_band8_distance_percentage] numeric(10,5)
,[velocity_band8_duration_percentage] numeric(10,5)
,[velocity_band8_average_effort_distance] numeric(10,5)
,[velocity_band8_average_effort_duration] numeric(10,5)
,[velocity2_band1_average_distance] numeric(10,5)
,[velocity2_band1_average_distance_session] numeric(10,5)
,[velocity2_band1_distance_percentage] numeric(10,5)
,[velocity2_band2_average_distance] numeric(10,5)
,[velocity2_band2_average_effort_count] int
,[velocity2_band2_average_distance_session] numeric(10,5)
,[velocity2_band2_average_effort_count_session] numeric(10,5)
,[velocity2_band2_distance_percentage] numeric(10,5)
,[velocity2_band3_average_distance] numeric(10,5)
,[velocity2_band3_average_effort_count] int
,[velocity2_band3_average_distance_session] numeric(10,5)
,[velocity2_band3_average_effort_count_session] numeric(10,5)
,[velocity2_band3_distance_percentage] numeric(10,5)
,[velocity2_band4_average_distance] numeric(10,5)
,[velocity2_band4_average_effort_count] int
,[velocity2_band4_average_distance_session] numeric(10,5)
,[velocity2_band4_average_effort_count_session] numeric(10,5)
,[velocity2_band4_distance_percentage] numeric(10,5)
,[velocity2_band5_average_distance] numeric(10,5)
,[velocity2_band5_average_effort_count] int
,[velocity2_band5_average_distance_session] numeric(10,5)
,[velocity2_band5_average_effort_count_session] numeric(10,5)
,[velocity2_band5_distance_percentage] numeric(10,5)
,[velocity2_band6_average_distance] numeric(10,5)
,[velocity2_band6_average_effort_count] int
,[velocity2_band6_average_distance_session] numeric(10,5)
,[velocity2_band6_average_effort_count_session] numeric(10,5)
,[velocity2_band6_distance_percentage] numeric(10,5)
,[velocity2_band7_average_distance] numeric(10,5)
,[velocity2_band7_average_effort_count] int
,[velocity2_band7_average_distance_session] numeric(10,5)
,[velocity2_band7_average_effort_count_session] numeric(10,5)
,[velocity2_band7_distance_percentage] numeric(10,5)
,[velocity2_band8_average_distance] numeric(10,5)
,[velocity2_band8_average_effort_count] int
,[velocity2_band8_average_distance_session] numeric(10,5)
,[velocity2_band8_average_effort_count_session] numeric(10,5)
,[velocity2_band8_distance_percentage] numeric(10,5)
,[gen2_velocity_band2_average_effort_distance] numeric(10,5)
,[gen2_velocity_band3_average_effort_distance] numeric(10,5)
,[gen2_velocity_band4_average_effort_distance] numeric(10,5)
,[gen2_velocity_band5_average_effort_distance] numeric(10,5)
,[gen2_velocity_band6_average_effort_distance] numeric(10,5)
,[gen2_velocity_band7_average_effort_distance] numeric(10,5)
,[gen2_velocity_band8_average_effort_distance] numeric(10,5)
,[gen2_velocity2_band2_average_effort_distance] numeric(10,5)
,[gen2_velocity2_band3_average_effort_distance] numeric(10,5)
,[gen2_velocity2_band4_average_effort_distance] numeric(10,5)
,[gen2_velocity2_band5_average_effort_distance] numeric(10,5)
,[gen2_velocity2_band6_average_effort_distance] numeric(10,5)
,[gen2_velocity2_band7_average_effort_distance] numeric(10,5)
,[gen2_velocity2_band8_average_effort_distance] numeric(10,5)
,[heart_rate_band1_average_distance] int
,[heart_rate_band1_average_duration] int
,[heart_rate_band1_average_distance_session] int
,[heart_rate_band1_average_duration_session] int
,[heart_rate_band1_distance_percentage] int
,[heart_rate_band1_duration_percentage] int
,[heart_rate_band2_average_distance] int
,[heart_rate_band2_average_duration] int
,[heart_rate_band2_average_effort_count] int
,[heart_rate_band2_average_distance_session] int
,[heart_rate_band2_average_duration_session] int
,[heart_rate_band2_average_effort_count_session] int
,[heart_rate_band2_distance_percentage] int
,[heart_rate_band2_duration_percentage] int
,[heart_rate_band3_average_distance] int
,[heart_rate_band3_average_duration] int
,[heart_rate_band3_average_effort_count] int
,[heart_rate_band3_average_distance_session] int
,[heart_rate_band3_average_duration_session] int
,[heart_rate_band3_average_effort_count_session] int
,[heart_rate_band3_distance_percentage] int
,[heart_rate_band3_duration_percentage] int
,[heart_rate_band4_average_distance] int
,[heart_rate_band4_average_duration] int
,[heart_rate_band4_average_effort_count] int
,[heart_rate_band4_average_distance_session] int
,[heart_rate_band4_average_duration_session] int
,[heart_rate_band4_average_effort_count_session] int
,[heart_rate_band4_distance_percentage] int
,[heart_rate_band4_duration_percentage] int
,[heart_rate_band5_average_distance] int
,[heart_rate_band5_average_duration] int
,[heart_rate_band5_average_effort_count] int
,[heart_rate_band5_average_distance_session] int
,[heart_rate_band5_average_duration_session] int
,[heart_rate_band5_average_effort_count_session] int
,[heart_rate_band5_distance_percentage] int
,[heart_rate_band5_duration_percentage] int
,[heart_rate_band6_average_distance] int
,[heart_rate_band6_average_duration] int
,[heart_rate_band6_average_effort_count] int
,[heart_rate_band6_average_distance_session] int
,[heart_rate_band6_average_duration_session] int
,[heart_rate_band6_average_effort_count_session] int
,[heart_rate_band6_distance_percentage] int
,[heart_rate_band6_duration_percentage] int
,[heart_rate_band7_average_distance] int
,[heart_rate_band7_average_duration] int
,[heart_rate_band7_average_effort_count] int
,[heart_rate_band7_average_distance_session] int
,[heart_rate_band7_average_duration_session] int
,[heart_rate_band7_average_effort_count_session] int
,[heart_rate_band7_distance_percentage] int
,[heart_rate_band7_duration_percentage] int
,[heart_rate_band8_average_distance] int
,[heart_rate_band8_average_duration] int
,[heart_rate_band8_average_effort_count] int
,[heart_rate_band8_average_distance_session] int
,[heart_rate_band8_average_duration_session] int
,[heart_rate_band8_average_effort_count_session] int
,[heart_rate_band8_distance_percentage] int
,[heart_rate_band8_duration_percentage] int
,[acceleration_band1_average_distance] numeric(10,5)
,[acceleration_band1_average_duration] numeric(10,5)
,[acceleration_band1_average_effort_count] int
,[acceleration_band1_average_distance_session] numeric(10,5)
,[acceleration_band1_average_duration_session] numeric(10,5)
,[acceleration_band1_average_effort_count_session] numeric(10,5)
,[acceleration_band1_distance_percentage] numeric(10,5)
,[acceleration_band1_duration_percentage] numeric(10,5)
,[acceleration_band2_average_distance] numeric(10,5)
,[acceleration_band2_average_duration] numeric(10,5)
,[acceleration_band2_average_effort_count] int
,[acceleration_band2_average_distance_session] numeric(10,5)
,[acceleration_band2_average_duration_session] numeric(10,5)
,[acceleration_band2_average_effort_count_session] numeric(10,5)
,[acceleration_band2_distance_percentage] numeric(10,5)
,[acceleration_band2_duration_percentage] numeric(10,5)
,[acceleration_band3_average_distance] numeric(10,5)
,[acceleration_band3_average_duration] numeric(10,5)
,[acceleration_band3_average_effort_count] int
,[acceleration_band3_average_distance_session] numeric(10,5)
,[acceleration_band3_average_duration_session] numeric(10,5)
,[acceleration_band3_average_effort_count_session] numeric(10,5)
,[acceleration_band3_distance_percentage] numeric(10,5)
,[acceleration_band3_duration_percentage] numeric(10,5)
,[acceleration_band4_average_distance] numeric(10,5)
,[acceleration_band4_average_duration] numeric(10,5)
,[acceleration_band4_average_effort_count] int
,[acceleration_band4_average_distance_session] numeric(10,1)
,[acceleration_band4_average_duration_session] numeric(10,5)
,[acceleration_band4_average_effort_count_session] numeric(10,5)
,[acceleration_band4_distance_percentage] numeric(10,5)
,[acceleration_band4_duration_percentage] numeric(10,5)
,[acceleration_band5_average_distance] numeric(10,5)
,[acceleration_band5_average_duration] numeric(10,5)
,[acceleration_band5_average_effort_count] int
,[acceleration_band5_average_distance_session] numeric(10,5)
,[acceleration_band5_average_duration_session] numeric(10,5)
,[acceleration_band5_average_effort_count_session] int
,[acceleration_band5_distance_percentage] numeric(10,5)
,[acceleration_band5_duration_percentage] numeric(10,5)
,[acceleration_band6_average_distance] numeric(10,5)
,[acceleration_band6_average_duration] numeric(10,5)
,[acceleration_band6_average_effort_count] int
,[acceleration_band6_average_distance_session] numeric(10,5)
,[acceleration_band6_average_duration_session] numeric(10,5)
,[acceleration_band6_average_effort_count_session] int
,[acceleration_band6_distance_percentage] numeric(10,5)
,[acceleration_band6_duration_percentage] numeric(10,5)
,[acceleration_band7_average_distance] numeric(10,5)
,[acceleration_band7_average_duration] numeric(10,5)
,[acceleration_band7_average_effort_count] int
,[acceleration_band7_average_distance_session] numeric(10,5)
,[acceleration_band7_average_duration_session] numeric(10,5)
,[acceleration_band7_average_effort_count_session] numeric(10,5)
,[acceleration_band7_distance_percentage] numeric(10,5)
,[acceleration_band7_duration_percentage] numeric(10,5)
,[acceleration_band8_average_distance] numeric(10,5)
,[acceleration_band8_average_duration] numeric(10,5)
,[acceleration_band8_average_effort_count] int
,[acceleration_band8_average_distance_session] numeric(10,5)
,[acceleration_band8_average_duration_session] numeric(10,5)
,[acceleration_band8_average_effort_count_session] numeric(10,5)
,[acceleration_band8_distance_percentage] numeric(10,5)
,[acceleration_band8_duration_percentage] numeric(10,5)
,[player_load_band1_average_distance] numeric(10,5)
,[player_load_band1_average_duration] numeric(10,5)
,[player_load_band1_average_distance_session] numeric(10,5)
,[player_load_band1_average_duration_session] numeric(10,5)
,[player_load_band1_distance_percentage] numeric(10,5)
,[player_load_band1_duration_percentage] numeric(10,5)
,[player_load_band2_average_distance] numeric(10,5)
,[player_load_band2_average_duration] numeric(10,5)
,[player_load_band2_average_effort_count] int
,[player_load_band2_average_distance_session] numeric(10,5)
,[player_load_band2_average_duration_session] numeric(10,5)
,[player_load_band2_average_effort_count_session] int
,[player_load_band2_distance_percentage] numeric(10,5)
,[player_load_band2_duration_percentage] numeric(10,5)
,[player_load_band3_average_distance] numeric(10,5)
,[player_load_band3_average_duration] numeric(10,5)
,[player_load_band3_average_effort_count] int
,[player_load_band3_average_distance_session] numeric(10,5)
,[player_load_band3_average_duration_session] numeric(10,5)
,[player_load_band3_average_effort_count_session] numeric(10,5)
,[player_load_band3_distance_percentage] numeric(10,5)
,[player_load_band3_duration_percentage] numeric(10,5)
,[player_load_band4_average_distance] numeric(10,5)
,[player_load_band4_average_duration] numeric(10,5)
,[player_load_band4_average_effort_count] int
,[player_load_band4_average_distance_session] numeric(10,5)
,[player_load_band4_average_duration_session] numeric(10,5)
,[player_load_band4_average_effort_count_session] numeric(10,5)
,[player_load_band4_distance_percentage] numeric(10,5)
,[player_load_band4_duration_percentage] numeric(10,5)
,[player_load_band5_average_distance] numeric(10,5)
,[player_load_band5_average_duration] numeric(10,5)
,[player_load_band5_average_effort_count] int
,[player_load_band5_average_distance_session] numeric(10,5)
,[player_load_band5_average_duration_session] numeric(10,5)
,[player_load_band5_average_effort_count_session] numeric(10,5)
,[player_load_band5_distance_percentage] numeric(10,5)
,[player_load_band5_duration_percentage] numeric(10,5)
,[player_load_band6_average_distance] numeric(10,5)
,[player_load_band6_average_duration] numeric(10,5)
,[player_load_band6_average_effort_count] int
,[player_load_band6_average_distance_session] numeric(10,5)
,[player_load_band6_average_duration_session] numeric(10,5)
,[player_load_band6_average_effort_count_session] numeric(10,5)
,[player_load_band6_distance_percentage] numeric(10,5)
,[player_load_band6_duration_percentage] numeric(10,5)
,[player_load_band7_average_distance] numeric(10,5)
,[player_load_band7_average_duration] numeric(10,5)
,[player_load_band7_average_effort_count] int
,[player_load_band7_average_distance_session] numeric(10,5)
,[player_load_band7_average_duration_session] numeric(10,5)
,[player_load_band7_average_effort_count_session] numeric(10,5)
,[player_load_band7_distance_percentage] numeric(10,5)
,[player_load_band7_duration_percentage] numeric(10,5)
,[player_load_band8_average_distance] numeric(10,5)
,[player_load_band8_average_duration] numeric(10,5)
,[player_load_band8_average_effort_count] int
,[player_load_band8_average_distance_session] numeric(10,5)
,[player_load_band8_average_duration_session] numeric(10,5)
,[player_load_band8_average_effort_count_session] numeric(10,5)
,[player_load_band8_distance_percentage] numeric(10,5)
,[player_load_band8_duration_percentage] numeric(10,5)
,[metabolic_power_band1_duration_percentage] numeric(10,5)
,[metabolic_power_band2_duration_percentage] numeric(10,5)
,[metabolic_power_band3_duration_percentage] numeric(10,5)
,[metabolic_power_band4_duration_percentage] numeric(10,5)
,[metabolic_power_band5_duration_percentage] numeric(10,5)
,[metabolic_power_band6_duration_percentage] numeric(10,5)
,[metabolic_power_band7_duration_percentage] numeric(10,5)
,[metabolic_power_band8_duration_percentage] numeric(10,5)
,[diveloadcentre_band1_average_count_session] numeric(10,5)
,[diveloadcentre_band2_average_count_session] numeric(10,5)
,[diveloadcentre_band3_average_count_session] numeric(10,5)
,[diveloadleft_band1_average_count_session] numeric(10,5)
,[diveloadleft_band2_average_count_session] numeric(10,5)
,[diveloadleft_band3_average_count_session] numeric(10,5)
,[diveloadright_band1_average_count_session] numeric(10,5)
,[diveloadright_band2_average_count_session] numeric(10,5)
,[diveloadright_band3_average_count_session] numeric(10,5)
,[timetofeetleft_band1_average_count_session] numeric(10,5)
,[timetofeetleft_band2_average_count_session] numeric(10,5)
,[timetofeetleft_band3_average_count_session] numeric(10,5)
,[timetofeetcentre_band1_average_count_session] numeric(10,5)
,[timetofeetcentre_band2_average_count_session] numeric(10,5)
,[timetofeetcentre_band3_average_count_session] numeric(10,5)
,[timetofeetright_band1_average_count_session] numeric(10,5)
,[timetofeetright_band2_average_count_session] numeric(10,5)
,[timetofeetright_band3_average_count_session] numeric(10,5)
,[metabolic_power_band1_average_power] numeric(10,5)
,[heart_rate_band1_average_beats_per_minute] int
,[tackles_band1_average_tackle_duration] int
,[metabolic_power_band2_average_power] numeric(10,5)
,[heart_rate_band2_average_beats_per_minute] int
,[tackles_band2_average_tackle_duration] int
,[metabolic_power_band3_average_power] numeric(10,5)
,[heart_rate_band3_average_beats_per_minute] int
,[tackles_band3_average_tackle_duration] int
,[metabolic_power_band4_average_power] numeric(10,5)
,[heart_rate_band4_average_beats_per_minute] int
,[tackles_band4_average_tackle_duration] int
,[metabolic_power_band5_average_power] numeric(10,5)
,[heart_rate_band5_average_beats_per_minute] int
,[tackles_band5_average_tackle_duration] int
,[metabolic_power_band6_average_power] numeric(10,5)
,[heart_rate_band6_average_beats_per_minute] int
,[tackles_band6_average_tackle_duration] int
,[metabolic_power_band7_average_power] numeric(10,5)
,[heart_rate_band7_average_beats_per_minute] int
,[tackles_band7_average_tackle_duration] int
,[metabolic_power_band8_average_power] numeric(10,5)
,[heart_rate_band8_average_beats_per_minute] int
,[tackles_band8_average_tackle_duration] int
,[rhie_average_bout_recovery] int
,[rhie_average_effort_recovery] int
,[rhie_average_effort_count] int
,[rhie_average_effort_duration] numeric(10,5)
,[dive_right_average_count_session] int
,[dive_left_average_count_session] int
,[dive_centre_average_count_session] int
,[ima_v1_free_run_duration_percentage] int
,[ima_v1_free_run_mean_stride_rate] int
,[ima_v2_free_run_duration_percentage] int
,[ima_v2_free_run_mean_stride_rate] int
,[imadiveintensityleft_band1_average_intensity] int
,[imadiveintensityright_band1_average_intensity] int
,[imadiveintensityleft_band1_average_count_session] int
,[imadiveintensityright_band1_average_count_session] int
,[imadiveintensityleft_band1_return_band1_average_return] int
,[imadiveintensityright_band1_return_band1_average_return] int
,[imadiveintensityleft_band1_return_band2_average_return] int
,[imadiveintensityright_band1_return_band2_average_return] int
,[imadiveintensityleft_band1_return_band3_average_return] int
,[imadiveintensityright_band1_return_band3_average_return] int
,[imadiveintensityleft_band1_return_band4_average_return] int
,[imadiveintensityright_band1_return_band4_average_return] int
,[imadiveintensityleft_band1_return_band5_average_return] int
,[imadiveintensityright_band1_return_band5_average_return] int
,[imadiveintensityleft_band1_return_band6_average_return] int
,[imadiveintensityright_band1_return_band6_average_return] int
,[imadiveintensityleft_band1_return_band7_average_return] int
,[imadiveintensityright_band1_return_band7_average_return] int
,[imadiveintensityleft_band1_return_band8_average_return] int
,[imadiveintensityright_band1_return_band8_average_return] int
,[imaimpacts_band1_average_count] int
,[imaimpacts_band1_average_count_session] int
,[imafreerunning_band1_average_duration_session] int
,[imafreerunning_band1_average_distance_session] int
,[imafreerunning_band1_average_player_load_session] int
,[ima_v2_free_run_band1_average_strides_session] int
,[ima_band1_old_average_accel_count_session] int
,[ima_band1_old_average_decel_count_session] int
,[ima_band1_old_average_left_count_session] int
,[ima_band1_old_average_right_count_session] int
,[ima_v1_free_run_band1_average_stride_rate] int
,[ima_v2_free_run_band1_average_stride_rate] int
,[imadiveintensityleft_band2_average_intensity] int
,[imadiveintensityright_band2_average_intensity] int
,[imadiveintensityleft_band2_average_count_session] int
,[imadiveintensityright_band2_average_count_session] int
,[imadiveintensityleft_band2_return_band1_average_return] int
,[imadiveintensityright_band2_return_band1_average_return] int
,[imadiveintensityleft_band2_return_band2_average_return] int
,[imadiveintensityright_band2_return_band2_average_return] int
,[imadiveintensityleft_band2_return_band3_average_return] int
,[imadiveintensityright_band2_return_band3_average_return] int
,[imadiveintensityleft_band2_return_band4_average_return] int
,[imadiveintensityright_band2_return_band4_average_return] int
,[imadiveintensityleft_band2_return_band5_average_return] int
,[imadiveintensityright_band2_return_band5_average_return] int
,[imadiveintensityleft_band2_return_band6_average_return] int
,[imadiveintensityright_band2_return_band6_average_return] int
,[imadiveintensityleft_band2_return_band7_average_return] int
,[imadiveintensityright_band2_return_band7_average_return] int
,[imadiveintensityleft_band2_return_band8_average_return] int
,[imadiveintensityright_band2_return_band8_average_return] int
,[imaimpacts_band2_average_count] int
,[imaimpacts_band2_average_count_session] int
,[imafreerunning_band2_average_duration_session] int
,[imafreerunning_band2_average_distance_session] int
,[imafreerunning_band2_average_player_load_session] int
,[ima_v2_free_run_band2_average_strides_session] int
,[ima_band2_old_average_accel_count_session] int
,[ima_band2_old_average_decel_count_session] int
,[ima_band2_old_average_left_count_session] int
,[ima_band2_old_average_right_count_session] int
,[ima_v1_free_run_band2_average_stride_rate] int
,[ima_v2_free_run_band2_average_stride_rate] int
,[imadiveintensityleft_band3_average_intensity] int
,[imadiveintensityright_band3_average_intensity] int
,[imadiveintensityleft_band3_average_count_session] int
,[imadiveintensityright_band3_average_count_session] int
,[imadiveintensityleft_band3_return_band1_average_return] int
,[imadiveintensityright_band3_return_band1_average_return] int
,[imadiveintensityleft_band3_return_band2_average_return] int
,[imadiveintensityright_band3_return_band2_average_return] int
,[imadiveintensityleft_band3_return_band3_average_return] int
,[imadiveintensityright_band3_return_band3_average_return] int
,[imadiveintensityleft_band3_return_band4_average_return] int
,[imadiveintensityright_band3_return_band4_average_return] int
,[imadiveintensityleft_band3_return_band5_average_return] int
,[imadiveintensityright_band3_return_band5_average_return] int
,[imadiveintensityleft_band3_return_band6_average_return] int
,[imadiveintensityright_band3_return_band6_average_return] int
,[imadiveintensityleft_band3_return_band7_average_return] int
,[imadiveintensityright_band3_return_band7_average_return] int
,[imadiveintensityleft_band3_return_band8_average_return] int
,[imadiveintensityright_band3_return_band8_average_return] int
,[imaimpacts_band3_average_count] int
,[imaimpacts_band3_average_count_session] int
,[imafreerunning_band3_average_duration_session] int
,[imafreerunning_band3_average_distance_session] int
,[imafreerunning_band3_average_player_load_session] int
,[ima_v2_free_run_band3_average_strides_session] int
,[ima_band3_old_average_accel_count_session] int
,[ima_band3_old_average_decel_count_session] int
,[ima_band3_old_average_left_count_session] int
,[ima_band3_old_average_right_count_session] int
,[ima_v1_free_run_band3_average_stride_rate] int
,[ima_v2_free_run_band3_average_stride_rate] int
,[imadiveintensityleft_band4_average_intensity] int
,[imadiveintensityright_band4_average_intensity] int
,[imadiveintensityleft_band4_average_count_session] int
,[imadiveintensityright_band4_average_count_session] int
,[imadiveintensityleft_band4_return_band1_average_return] int
,[imadiveintensityright_band4_return_band1_average_return] int
,[imadiveintensityleft_band4_return_band2_average_return] int
,[imadiveintensityright_band4_return_band2_average_return] int
,[imadiveintensityleft_band4_return_band3_average_return] int
,[imadiveintensityright_band4_return_band3_average_return] int
,[imadiveintensityleft_band4_return_band4_average_return] int
,[imadiveintensityright_band4_return_band4_average_return] int
,[imadiveintensityleft_band4_return_band5_average_return] int
,[imadiveintensityright_band4_return_band5_average_return] int
,[imadiveintensityleft_band4_return_band6_average_return] int
,[imadiveintensityright_band4_return_band6_average_return] int
,[imadiveintensityleft_band4_return_band7_average_return] int
,[imadiveintensityright_band4_return_band7_average_return] int
,[imadiveintensityleft_band4_return_band8_average_return] int
,[imadiveintensityright_band4_return_band8_average_return] int
,[imaimpacts_band4_average_count] int
,[imaimpacts_band4_average_count_session] int
,[imafreerunning_band4_average_duration_session] int
,[imafreerunning_band4_average_distance_session] int
,[imafreerunning_band4_average_player_load_session] int
,[ima_v2_free_run_band4_average_strides_session] int
,[ima_v1_free_run_band4_average_stride_rate] int
,[ima_v2_free_run_band4_average_stride_rate] int
,[imadiveintensityleft_band5_average_intensity] int
,[imadiveintensityright_band5_average_intensity] int
,[imadiveintensityleft_band5_average_count_session] int
,[imadiveintensityright_band5_average_count_session] int
,[imadiveintensityleft_band5_return_band1_average_return] int
,[imadiveintensityright_band5_return_band1_average_return] int
,[imadiveintensityleft_band5_return_band2_average_return] int
,[imadiveintensityright_band5_return_band2_average_return] int
,[imadiveintensityleft_band5_return_band3_average_return] int
,[imadiveintensityright_band5_return_band3_average_return] int
,[imadiveintensityleft_band5_return_band4_average_return] int
,[imadiveintensityright_band5_return_band4_average_return] int
,[imadiveintensityleft_band5_return_band5_average_return] int
,[imadiveintensityright_band5_return_band5_average_return] int
,[imadiveintensityleft_band5_return_band6_average_return] int
,[imadiveintensityright_band5_return_band6_average_return] int
,[imadiveintensityleft_band5_return_band7_average_return] int
,[imadiveintensityright_band5_return_band7_average_return] int
,[imadiveintensityleft_band5_return_band8_average_return] int
,[imadiveintensityright_band5_return_band8_average_return] int
,[imaimpacts_band5_average_count] int
,[imaimpacts_band5_average_count_session] int
,[imafreerunning_band5_average_duration_session] int
,[imafreerunning_band5_average_distance_session] int
,[imafreerunning_band5_average_player_load_session] int
,[ima_v2_free_run_band5_average_strides_session] int
,[ima_v1_free_run_band5_average_stride_rate] int
,[ima_v2_free_run_band5_average_stride_rate] int
,[imadiveintensityleft_band6_average_intensity] int
,[imadiveintensityright_band6_average_intensity] int
,[imadiveintensityleft_band6_average_count_session] int
,[imadiveintensityright_band6_average_count_session] int
,[imadiveintensityleft_band6_return_band1_average_return] int
,[imadiveintensityright_band6_return_band1_average_return] int
,[imadiveintensityleft_band6_return_band2_average_return] int
,[imadiveintensityright_band6_return_band2_average_return] int
,[imadiveintensityleft_band6_return_band3_average_return] int
,[imadiveintensityright_band6_return_band3_average_return] int
,[imadiveintensityleft_band6_return_band4_average_return] int
,[imadiveintensityright_band6_return_band4_average_return] int
,[imadiveintensityleft_band6_return_band5_average_return] int
,[imadiveintensityright_band6_return_band5_average_return] int
,[imadiveintensityleft_band6_return_band6_average_return] int
,[imadiveintensityright_band6_return_band6_average_return] int
,[imadiveintensityleft_band6_return_band7_average_return] int
,[imadiveintensityright_band6_return_band7_average_return] int
,[imadiveintensityleft_band6_return_band8_average_return] int
,[imadiveintensityright_band6_return_band8_average_return] int
,[imaimpacts_band6_average_count] int
,[imaimpacts_band6_average_count_session] int
,[imafreerunning_band6_average_duration_session] int
,[imafreerunning_band6_average_distance_session] int
,[imafreerunning_band6_average_player_load_session] int
,[ima_v2_free_run_band6_average_strides_session] int
,[ima_v1_free_run_band6_average_stride_rate] int
,[ima_v2_free_run_band6_average_stride_rate] int
,[imadiveintensityleft_band7_average_intensity] int
,[imadiveintensityright_band7_average_intensity] int
,[imadiveintensityleft_band7_average_count_session] int
,[imadiveintensityright_band7_average_count_session] int
,[imadiveintensityleft_band7_return_band1_average_return] int
,[imadiveintensityright_band7_return_band1_average_return] int
,[imadiveintensityleft_band7_return_band2_average_return] int
,[imadiveintensityright_band7_return_band2_average_return] int
,[imadiveintensityleft_band7_return_band3_average_return] int
,[imadiveintensityright_band7_return_band3_average_return] int
,[imadiveintensityleft_band7_return_band4_average_return] int
,[imadiveintensityright_band7_return_band4_average_return] int
,[imadiveintensityleft_band7_return_band5_average_return] int
,[imadiveintensityright_band7_return_band5_average_return] int
,[imadiveintensityleft_band7_return_band6_average_return] int
,[imadiveintensityright_band7_return_band6_average_return] int
,[imadiveintensityleft_band7_return_band7_average_return] int
,[imadiveintensityright_band7_return_band7_average_return] int
,[imadiveintensityleft_band7_return_band8_average_return] int
,[imadiveintensityright_band7_return_band8_average_return] int
,[imaimpacts_band7_average_count] int
,[imaimpacts_band7_average_count_session] int
,[imafreerunning_band7_average_duration_session] int
,[imafreerunning_band7_average_distance_session] int
,[imafreerunning_band7_average_player_load_session] int
,[ima_v2_free_run_band7_average_strides_session] int
,[ima_v1_free_run_band7_average_stride_rate] int
,[ima_v2_free_run_band7_average_stride_rate] int
,[imadiveintensityleft_band8_average_intensity] int
,[imadiveintensityright_band8_average_intensity] int
,[imadiveintensityleft_band8_average_count_session] int
,[imadiveintensityright_band8_average_count_session] int
,[imadiveintensityleft_band8_return_band1_average_return] int
,[imadiveintensityright_band8_return_band1_average_return] int
,[imadiveintensityleft_band8_return_band2_average_return] int
,[imadiveintensityright_band8_return_band2_average_return] int
,[imadiveintensityleft_band8_return_band3_average_return] int
,[imadiveintensityright_band8_return_band3_average_return] int
,[imadiveintensityleft_band8_return_band4_average_return] int
,[imadiveintensityright_band8_return_band4_average_return] int
,[imadiveintensityleft_band8_return_band5_average_return] int
,[imadiveintensityright_band8_return_band5_average_return] int
,[imadiveintensityleft_band8_return_band6_average_return] int
,[imadiveintensityright_band8_return_band6_average_return] int
,[imadiveintensityleft_band8_return_band7_average_return] int
,[imadiveintensityright_band8_return_band7_average_return] int
,[imadiveintensityleft_band8_return_band8_average_return] int
,[imadiveintensityright_band8_return_band8_average_return] int
,[imaimpacts_band8_average_count] int
,[imaimpacts_band8_average_count_session] int
,[imafreerunning_band8_average_duration_session] int
,[imafreerunning_band8_average_distance_session] int
,[imafreerunning_band8_average_player_load_session] int
,[ima_v2_free_run_band8_average_strides_session] int
,[ima_v1_free_run_band8_average_stride_rate] int
,[ima_v2_free_run_band8_average_stride_rate] int
,[int_day_id] int
,[max_intensity_interval_dist_interval_1_start_time_h] nvarchar(100)
,[max_intensity_interval_dist_interval_1_end_time_h] nvarchar(100)
,[max_intensity_interval_dist_interval_2_start_time_h] nvarchar(100)
,[max_intensity_interval_dist_interval_2_end_time_h] nvarchar(100)
,[max_intensity_interval_dist_interval_3_start_time_h] nvarchar(100)
,[max_intensity_interval_dist_interval_3_end_time_h] nvarchar(100)
,[max_intensity_interval_pl_interval_1_start_time_h] nvarchar(100)
,[max_intensity_interval_pl_interval_1_end_time_h] nvarchar(100)
,[max_intensity_interval_pl_interval_2_start_time_h] nvarchar(100)
,[max_intensity_interval_pl_interval_2_end_time_h] nvarchar(100)
,[max_intensity_interval_pl_interval_3_start_time_h] nvarchar(100)
,[max_intensity_interval_pl_interval_3_end_time_h] nvarchar(100)
)
